import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema64/Serialization_EventArgs";
import type { Request, Response } from "../Rpc";

export const json : (Request<KnownTypeSchema | UnknownTypeSchema> | Response<KnownTypeSchema | UnknownTypeSchema>)[] = [
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":2,"arguments":[]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":3,"sourceClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"eventId":3,"arguments":[{"$":"list","values":[["Int64",1],["Int64",2]]},{"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":-5}]},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":4,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":-5},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":4,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":3,"sourceClientId":2,"targetClientId":1,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":1,"arguments":[]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":6,"sourceClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":-5},"eventId":-1,"arguments":[["Int64",2],["Int64",0],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":6,"sourceClientId":2,"targetClientId":1,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":-5},"methodId":-1,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":1,"targetClientId":2,"response":{"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":-2}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":8,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":8,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-2,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":1,"targetClientId":2,"response":true},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-3,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":1,"targetClientId":2,"response":["Int64",3]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-2,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":1,"targetClientId":2,"response":true},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-3,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":1,"targetClientId":2,"response":["Int64",4]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-2,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":1,"targetClientId":2,"response":true},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-3,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":1,"targetClientId":2,"response":["Int64",6]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"methodId":-2,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":1,"targetClientId":2,"response":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":16,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":-2},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":16,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":17,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":17,"sourceClientId":1,"targetClientId":2}
];
