import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema64/Serialization_CollectionDict_Nested_InByref_OutByref";
import type { Request, Response } from "../Rpc";

export const json : (Request<KnownTypeSchema | UnknownTypeSchema> | Response<KnownTypeSchema | UnknownTypeSchema>)[] = [
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":1,"arguments":[{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-4}]},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-4},"remoteClientId":1,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-4},"methodId":-5,"arguments":[["Int64",0]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":2,"targetClientId":1,"response":{"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":-6}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":5,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":1,"typeId":-6},"remoteClientId":1,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":5,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":6,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":1,"typeId":-6},"methodId":-15,"arguments":[["Int64",4],"D"]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":6,"sourceClientId":2,"targetClientId":1,"response":null},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":7,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":1,"typeId":-6},"remoteClientId":1,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":7,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":1,"targetClientId":2,"response":{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-4}},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":8,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-4},"methodId":-5,"arguments":[["Int64",0]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":8,"sourceClientId":2,"targetClientId":1,"response":{"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":-6}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":9,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"remoteClientId":1,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":9,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-13,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":2,"targetClientId":1,"response":["Int64",5]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-14,"arguments":[["Int64",1]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":2,"targetClientId":1,"response":"A"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-14,"arguments":[["Int64",2]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":2,"targetClientId":1,"response":"B"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-14,"arguments":[["Int64",3]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":2,"targetClientId":1,"response":"C"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-14,"arguments":[["Int64",4]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":2,"targetClientId":1,"response":"D"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"methodId":-14,"arguments":[["Int64",5]]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":2,"targetClientId":1,"response":"E"},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":16,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":2,"typeId":-6},"remoteClientId":1,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":16,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":17,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":17,"sourceClientId":1,"targetClientId":2}
];
