import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema64/Serialization_Inheritance";
import type { Request, Response } from "../Rpc";

export const json : (Request<KnownTypeSchema | UnknownTypeSchema> | Response<KnownTypeSchema | UnknownTypeSchema>)[] = [
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":4},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":4},"methodId":6,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":1,"targetClientId":2,"response":{"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":2}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":2},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":2},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":1,"targetClientId":2,"response":""},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":2},"methodId":3,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":6,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":2},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":6,"sourceClientId":1,"targetClientId":2,"response":"One"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":4},"methodId":7,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":1,"targetClientId":2,"response":{"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":8}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":8,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":8},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":8,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":8},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":1,"targetClientId":2,"response":""},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":8},"methodId":9,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":10,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":8},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":1,"targetClientId":2,"response":"Two"},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":4},"methodId":5,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":12,"sourceClientId":1,"targetClientId":2,"response":{"$":"system::RpcObjectReference","clientId":1,"objectId":3,"typeId":0}},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":13,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":13,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":14,"sourceClientId":1,"targetClientId":2,"response":""},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":1,"targetClientId":2,"response":""},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":16,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"methodId":1,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":16,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":17,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"methodId":11,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":17,"sourceClientId":1,"targetClientId":2,"response":"Derived"},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":18,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":3,"typeId":0},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":18,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":19,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":2,"typeId":8},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":19,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":20,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":1,"typeId":2},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":20,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":21,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":4},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":21,"sourceClientId":1,"targetClientId":2}
];
