import type { KnownTypeSchema, UnknownTypeSchema } from "./Serialization_EventOblist";
import type { Request, Response } from "../Rpc";

export const json : (Request<KnownTypeSchema | UnknownTypeSchema> | Response<KnownTypeSchema | UnknownTypeSchema>)[] = [
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":1,"sourceClientId":1,"targetClientId":2},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":2,"arguments":[{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-5}]},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"remoteClientId":1,"hold":true},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":3,"sourceClientId":2,"targetClientId":1},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":2,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":1,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"methodId":-7,"arguments":[["Int64",10]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":6,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",0],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":6,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":5,"sourceClientId":2,"targetClientId":1,"response":["Int64",0]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"methodId":-8,"arguments":[["Int64",1],["Int64",20]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":8,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",1],["Int64",0],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":8,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":7,"sourceClientId":2,"targetClientId":1,"response":["Int64",1]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"methodId":-6,"arguments":[["Int64",0],["Int64",30]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":10,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",1],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":10,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":9,"sourceClientId":2,"targetClientId":1,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"methodId":-9,"arguments":[["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":12,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",1],["Int64",1],["Int64",0]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":12,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":11,"sourceClientId":2,"targetClientId":1,"response":true},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":1,"targetClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"methodId":-10,"arguments":[]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":14,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",1],["Int64",0]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":14,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":13,"sourceClientId":2,"targetClientId":1,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":4,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"methodId":3,"arguments":[]},
  {"rpcMethod":"IObjectOps_InvokeMethod","rpcRequestId":15,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":16,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",0],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":16,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":17,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",1],["Int64",0],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":17,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":18,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",1],["Int64",1]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":18,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":19,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",1],["Int64",1],["Int64",0]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":19,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":20,"sourceClientId":2,"ref":{"clientId":2,"objectId":0,"typeId":-5},"eventId":-1,"arguments":[["Int64",0],["Int64",1],["Int64",0]]},
  {"rpcMethod":"IObjectEventOps_InvokeEvent","rpcRequestId":20,"sourceClientId":1,"targetClientId":2,"response":null},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":21,"sourceClientId":2,"targetClientId":1,"ref":{"clientId":1,"objectId":0,"typeId":0},"remoteClientId":2,"hold":false},
  {"rpcMethod":"IObjectOps_ObjectHold","rpcRequestId":21,"sourceClientId":1,"targetClientId":2}
];
