/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/BindCustomInterface2.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_BINDCUSTOMINTERFACE2
#define VCZH_WORKFLOW_COMPILER_GENERATED_BINDCUSTOMINTERFACE2

#include "../Source/CppTypes.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_BindCustomInterface2_Bind_;
	class __vwsnc1_BindCustomInterface2_Bind__vl_reflection_description_IValueSubscription;
	class __vwsnc2_BindCustomInterface2_main__IAdder2;
}

class ISummer2;
class IAdder2;

class ISummer2 : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<ISummer2>
{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
	friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<ISummer2>;
#endif
public:
	virtual ::vl::vint GetSum() = 0;
	::vl::Event<void()> SumChanged;
};

class IAdder2 : public virtual ::ISummer2, public ::vl::reflection::Description<IAdder2>
{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
	friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IAdder2>;
#endif
public:
	virtual void Add(::vl::vint value) = 0;
};

/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class BindCustomInterface2
	{
	public:

		::vl::WString s;

		::vl::Ptr<::vl::reflection::description::IValueSubscription> Bind(::vl::Ptr<::ISummer2> summer);
		void Execute(::vl::Ptr<::IAdder2> adder);
		::vl::WString main();

		static BindCustomInterface2& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_BindCustomInterface2_Bind_
	{
		__vwsnf1_BindCustomInterface2_Bind_();

		void operator()(const ::vl::reflection::description::Value& value) const;
	};

	class __vwsnc1_BindCustomInterface2_Bind__vl_reflection_description_IValueSubscription : public ::vl::Object, public virtual ::vl::reflection::description::IValueSubscription
	{
	public:
		::vl::Ptr<::ISummer2> summer;

		__vwsnc1_BindCustomInterface2_Bind__vl_reflection_description_IValueSubscription(::vl::Ptr<::ISummer2> __vwsnctor_summer);

		::vl::Ptr<::ISummer2> __vwsn_bind_cache_0;
		::vl::Ptr<::vl::reflection::description::IEventHandler> __vwsn_bind_handler_0_0;
		bool __vwsn_bind_opened_ = false;
		bool __vwsn_bind_closed_ = false;
		void __vwsn_bind_activator_();
		void __vwsn_bind_callback_0_0();
		bool Open() override;
		bool Update() override;
		bool Close() override;
	};

	class __vwsnc2_BindCustomInterface2_main__IAdder2 : public ::vl::Object, public virtual ::IAdder2
	{
	public:
		__vwsnc2_BindCustomInterface2_main__IAdder2();

		::vl::vint __vwsn_prop_Sum = 0;
		::vl::vint GetSum() override;
		void SetSum(::vl::vint __vwsn_value_);
		void Add(::vl::vint value) override;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
