/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/NestedLambda.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "NestedLambdaReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(IA)
			IMPL_CPP_TYPE_INFO(IB)

#define _ ,
			BEGIN_INTERFACE_MEMBER(::IA)
				CLASS_MEMBER_METHOD(Calculate, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetA, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetA, { L"value" })
				CLASS_MEMBER_EVENT(AChanged)
				CLASS_MEMBER_PROPERTY_EVENT(A, GetA, SetA, AChanged)
			END_INTERFACE_MEMBER(::IA)

			BEGIN_INTERFACE_MEMBER(::IB)
				CLASS_MEMBER_METHOD(Calculate, NO_PARAMETER)
				CLASS_MEMBER_METHOD(GetB, NO_PARAMETER)
				CLASS_MEMBER_METHOD(SetB, { L"value" })
				CLASS_MEMBER_EVENT(BChanged)
				CLASS_MEMBER_PROPERTY_EVENT(B, GetB, SetB, BChanged)
			END_INTERFACE_MEMBER(::IB)

#undef _
			class NestedLambdaTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::IA)
					ADD_TYPE_INFO(::IB)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif

			bool LoadNestedLambdaTypes()
			{
#ifndef VCZH_DEBUG_NO_REFLECTION
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(MakePtr<NestedLambdaTypeLoader>());
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif
