/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/NewCustomInterfaceDtor2.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "NewCustomInterfaceDtor2.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, NewCustomInterfaceDtor2Reflection.h) */
#include "NewCustomInterfaceDtor2Reflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::NewCustomInterfaceDtor2::
#define GLOBAL_NAME ::vl_workflow_global::NewCustomInterfaceDtor2::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::NewCustomInterfaceDtor2::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_NewCustomInterfaceDtor2)
	vl_workflow_global::NewCustomInterfaceDtor2 instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Unmanaged(L"");
	FINALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Empty;
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_NewCustomInterfaceDtor2)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	::vl::WString NewCustomInterfaceDtor2::main()
	{
		auto obj = static_cast<::IMyInterfaceDtor2*>(new ::vl_workflow_global::__vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2());
		auto r = ::vl::__vwsn::This(obj)->GetResult();
		::vl::__vwsn::This(obj)->Dispose(true);
		return (((::vl::WString::Unmanaged(L"") + r) + ::vl::WString::Unmanaged(L"")) + GLOBAL_NAME s);
	}

	NewCustomInterfaceDtor2& NewCustomInterfaceDtor2::Instance()
	{
		return Getvl_workflow_global_NewCustomInterfaceDtor2().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2::__vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2()
	{
		this->value = static_cast<::vl::vint>(42);
	}

	::vl::vint __vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2::DoubleValue()
	{
		return (value * static_cast<::vl::vint>(2));
	}

	::vl::WString __vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2::GetResult()
	{
		return ((::vl::WString::Unmanaged(L"[") + ::vl::__vwsn::ToString(this->DoubleValue())) + ::vl::WString::Unmanaged(L"]"));
	}

	__vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2::~__vwsnc1_NewCustomInterfaceDtor2_main__IMyInterfaceDtor2()
	{
		(GLOBAL_NAME s = ((((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(this->DoubleValue())) + ::vl::WString::Unmanaged(L"]")));
	}

}

/***********************************************************************
Class (::IMyInterfaceDtor2)
***********************************************************************/

#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
