/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/NewCustomInterfaceDtor3.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "NewCustomInterfaceDtor3.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, NewCustomInterfaceDtor3Reflection.h) */
#include "NewCustomInterfaceDtor3Reflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::NewCustomInterfaceDtor3::
#define GLOBAL_NAME ::vl_workflow_global::NewCustomInterfaceDtor3::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::NewCustomInterfaceDtor3::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_NewCustomInterfaceDtor3)
	vl_workflow_global::NewCustomInterfaceDtor3 instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Unmanaged(L"");
	FINALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Empty;
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_NewCustomInterfaceDtor3)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	::vl::WString NewCustomInterfaceDtor3::main()
	{
		auto x = ::vl::Ptr<::MyDtorClass>(new ::MyDtorClass(static_cast<::vl::vint>(5)));
		auto obj = ::vl::__vwsn::This(x.Obj())->CreateInterface();
		auto r = ::vl::__vwsn::This(obj)->GetResult();
		::vl::__vwsn::This(obj)->Dispose(true);
		return (((::vl::WString::Unmanaged(L"") + r) + ::vl::WString::Unmanaged(L"")) + GLOBAL_NAME s);
	}

	NewCustomInterfaceDtor3& NewCustomInterfaceDtor3::Instance()
	{
		return Getvl_workflow_global_NewCustomInterfaceDtor3().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3::__vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3(::MyDtorClass* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	::vl::WString __vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3::GetResult()
	{
		return ((((::vl::WString::Unmanaged(L"[") + ::vl::__vwsn::ToString(::MyDtorClass::GetBase())) + ::vl::WString::Unmanaged(L":")) + ::vl::__vwsn::ToString(__vwsnthis_0->factor)) + ::vl::WString::Unmanaged(L"]"));
	}

	__vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3::~__vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3()
	{
		(GLOBAL_NAME s = ((((((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::MyDtorClass::GetBase())) + ::vl::WString::Unmanaged(L":")) + ::vl::__vwsn::ToString(__vwsnthis_0->factor)) + ::vl::WString::Unmanaged(L"]")));
	}

}

/***********************************************************************
Class (::IMyInterfaceDtor3)
***********************************************************************/

/***********************************************************************
Class (::MyDtorClass)
***********************************************************************/

MyDtorClass::MyDtorClass(::vl::vint f)
	: factor(static_cast<::vl::vint>(0))
{
	(this->factor = f);
}

::vl::vint MyDtorClass::GetBase()
{
	return static_cast<::vl::vint>(10);
}

::IMyInterfaceDtor3* MyDtorClass::CreateInterface()
{
	return static_cast<::IMyInterfaceDtor3*>(new ::vl_workflow_global::__vwsnc1_NewCustomInterfaceDtor3_MyDtorClass_CreateInterface__IMyInterfaceDtor3(this));
}

#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
