/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/StructCtor.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_STRUCTCTOR
#define VCZH_WORKFLOW_COMPILER_GENERATED_STRUCTCTOR

#include "../Source/CppTypes.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace __vwsn_structs
{
	struct _depended_structs_B
	{
		::test::Point data;

		auto operator<=>(const _depended_structs_B&) const = default;
	};

	struct _depended_structs_A
	{
		::__vwsn_structs::_depended_structs_B data;

		auto operator<=>(const _depended_structs_A&) const = default;
	};

	struct _depended_structs_C
	{
		::__vwsn_structs::_depended_structs_A data;

		auto operator<=>(const _depended_structs_C&) const = default;
	};

	struct _depended_structs_D
	{
		::__vwsn_structs::_depended_structs_B data;

		auto operator<=>(const _depended_structs_D&) const = default;
	};

}
namespace depended_structs
{
	using A = ::__vwsn_structs::_depended_structs_A;
	using B = ::__vwsn_structs::_depended_structs_B;
	using C = ::__vwsn_structs::_depended_structs_C;
	using D = ::__vwsn_structs::_depended_structs_D;

}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class StructCtor
	{
	public:

		::vl::vint Do(::test::Point p);
		::vl::WString main();

		static StructCtor& Instance();
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
