/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Codegen/WorkflowMultiFiles.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_WORKFLOWMULTIFILES_DP2
#define VCZH_WORKFLOW_COMPILER_GENERATED_WORKFLOWMULTIFILES_DP2

#include "WorkflowMultiFiles.h"
#include "WorkflowMultiFiles_Bird.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses-equality"
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#endif

namespace multifiles
{
	class HuntingObject : public ::vl::Object, public ::vl::reflection::Description<HuntingObject>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<HuntingObject>;
#endif
	public:
		class Inside;

		class Inside : public ::multifiles::Bird, public ::vl::reflection::Description<Inside>
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<Inside>;
#endif
		public:
			Inside();
		};
		HuntingObject();
	};

	class Leopard : public ::multifiles::Cat, public ::multifiles::HuntingObject, public ::vl::reflection::Description<Leopard>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<Leopard>;
#endif
	public:
		Leopard();
	};

	class Tiger : public ::multifiles::Cat, public ::multifiles::HuntingObject, public ::vl::reflection::Description<Tiger>
	{
#ifndef VCZH_DEBUG_NO_REFLECTION
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<Tiger>;
#endif
	public:
		Tiger();
	};

}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

#endif
