import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema64/Serialization_CollectionDict_Interface_InByref_OutByref";

export const json : (KnownTypeSchema | UnknownTypeSchema)[] = [
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-6},
  ["Int64",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":2},
  null,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-6},
  ["Int64",5],
  ["Int64",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int64",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int64",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  ["Int64",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":2},
  ["Int64",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":4,"typeId":2},
  "D",
  ["Int64",5],
  ["Int64",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":5,"typeId":2},
  "A",
  ["Int64",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":6,"typeId":2},
  "B",
  ["Int64",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":7,"typeId":2},
  "C",
  ["Int64",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":2},
  ["Int64",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":8,"typeId":2},
  "E",
  "D"
];
