import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema64/Serialization_CollectionDict_Interface_InByval_OutByref";

export const json : (KnownTypeSchema | UnknownTypeSchema)[] = [
  {"$":"map","values":[[["Int64",1],{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2}],[["Int64",2],{"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2}],[["Int64",3],{"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2}]]},
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":-6},
  ["Int64",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  null,
  ["Int64",5],
  ["Int64",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  ["Int64",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int64",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int64",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":2},
  ["Int64",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  "A",
  "B",
  "C",
  "E",
  ["Int64",5],
  ["Int64",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  ["Int64",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int64",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int64",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":3,"typeId":2},
  "D",
  ["Int64",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2}
];
