/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/CollectionDict_Interface_Nested_PropByref.txt; ../Resources/Rpc/CollectionDict_Interface_Nested_PropByref_Test.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_COLLECTIONDICT_INTERFACE_NESTED_PROPBYREFREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_COLLECTIONDICT_INTERFACE_NESTED_PROPBYREFREFLECTION

#include "CollectionDict_Interface_Nested_PropByref.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IService)
			DECL_TYPE_INFO(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IValue)
			DECL_TYPE_INFO(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IService)
			DECL_TYPE_INFO(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IValue)
			DECL_TYPE_INFO(::rpcops_IOps_Rpc_CollectionDict_Interface_Nested_PropByref)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IService)
				::vl::Ptr<::vl::reflection::description::IValueDictionary> GetList() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetList);
				}
				void SetList(::vl::Ptr<::vl::reflection::description::IValueDictionary> __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(SetList, __vwsn_value_);
				}
			END_INTERFACE_PROXY(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IService)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IValue)
				::vl::WString GetValue() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetValue);
				}
			END_INTERFACE_PROXY(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IValue)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::rpcops_IOps_Rpc_CollectionDict_Interface_Nested_PropByref)
				::vl::Ptr<::vl::reflection::description::IValueDictionary> InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IService_GetList(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IService_GetList, ref);
				}
				void InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IService_SetList(::vl::rpc_controller::RpcObjectReference ref, ::vl::Ptr<::vl::reflection::description::IValueDictionary> __vwsn_value_) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IService_SetList, ref, __vwsn_value_);
				}
				::vl::WString InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IValue_GetValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcCollectionDict__Interface__Nested__InByref__PropByref__IValue_GetValue, ref);
				}
			END_INTERFACE_PROXY(::rpcops_IOps_Rpc_CollectionDict_Interface_Nested_PropByref)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IService, ::RpcCollectionDict::Interface::Nested::InByref::PropByref::IService, ::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_PROXY(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IService)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IValue, ::RpcCollectionDict::Interface::Nested::InByref::PropByref::IValue, ::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_PROXY(::RpcCollectionDict::Interface::Nested::InByref::PropByref::IRpcWrapper_IValue)
#endif
#endif

			extern bool LoadRpc_CollectionDict_Interface_Nested_PropByrefTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
