/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/CollectionDict_Interface_InByval_OutByval.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "CollectionDict_Interface_InByval_OutByval.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, CollectionDict_Interface_InByval_OutByvalReflection.h) */
#include "CollectionDict_Interface_InByval_OutByvalReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Rpc_CollectionDict_Interface_InByval_OutByval::
#define GLOBAL_NAME ::vl_workflow_global::Rpc_CollectionDict_Interface_InByval_OutByval::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Rpc_CollectionDict_Interface_InByval_OutByval::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_CollectionDict_Interface_InByval_OutByval)
	vl_workflow_global::Rpc_CollectionDict_Interface_InByval_OutByval instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.xsService = ::vl::reflection::description::IValueDictionary::Create();
		instance.rpctype_RpcCollectionDict__Interface__InByval__OutByval__IValue = static_cast<::vl::vint>(0);
		instance.rpctype_RpcCollectionDict__Interface__InByval__OutByval__IService = static_cast<::vl::vint>(1);
		instance.rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IValue_GetValue = static_cast<::vl::vint>(2);
		instance.rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IService_DoList = static_cast<::vl::vint>(3);
	FINALIZE_GLOBAL_STORAGE_CLASS

		instance.xsService = nullptr;
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_CollectionDict_Interface_InByval_OutByval)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue> Rpc_CollectionDict_Interface_InByval_OutByval::MakeValue(::vl::vint value)
	{
		return GLOBAL_NAME MakeValue((::vl::WString::Unmanaged(L"") + ::vl::__vwsn::ToString(value)));
	}

	::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue> Rpc_CollectionDict_Interface_InByval_OutByval::MakeValue(const ::vl::WString& value)
	{
		return ::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue>(new ::vl_workflow_global::__vwsnc1_Rpc_CollectionDict_Interface_InByval_OutByval_MakeValue__RpcCollectionDict_Interface_InByval_OutByval_IValue(value));
	}

	void Rpc_CollectionDict_Interface_InByval_OutByval::CheckValue(::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue> value, bool shouldBeWrapper, const ::vl::WString& name)
	{
		auto valueObj = ::vl::__vwsn::Box(value);
		if (shouldBeWrapper)
		{
			if ((! static_cast<bool>(::vl::__vwsn::UnboxWeak<::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>>(valueObj))))
			{
				throw ::vl::Exception(((::vl::WString::Unmanaged(L"") + name) + ::vl::WString::Unmanaged(L" should be a wrapper object")));
			}
		}
		else
		{
			if (static_cast<bool>(::vl::__vwsn::UnboxWeak<::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>>(valueObj)))
			{
				throw ::vl::Exception(((::vl::WString::Unmanaged(L"") + name) + ::vl::WString::Unmanaged(L" should be a local object")));
			}
		}
	}

	void Rpc_CollectionDict_Interface_InByval_OutByval::CheckServiceItems(::vl::Ptr<::vl::reflection::description::IValueDictionary> xs)
	{
		{
			auto __vwsn_for_begin_i = static_cast<::vl::vint>(1);
			auto __vwsn_for_end_i = ::vl::__vwsn::This(xs.Obj())->GetCount();
			auto i = __vwsn_for_begin_i;
			while ((i <= __vwsn_for_end_i))
			{
				{
					GLOBAL_NAME CheckValue(::vl::__vwsn::Unbox<::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue>>(::vl::__vwsn::This(xs.Obj())->Get(::vl::__vwsn::Box(i))), (i != static_cast<::vl::vint>(4)), ((::vl::WString::Unmanaged(L"xsService[") + ::vl::__vwsn::ToString(i)) + ::vl::WString::Unmanaged(L"]")));
				}
				(i = (i + static_cast<::vl::vint>(1)));
			}
		}
	}

	void Rpc_CollectionDict_Interface_InByval_OutByval::CheckClientItems(::vl::Ptr<::vl::reflection::description::IValueDictionary> xs)
	{
		{
			auto __vwsn_for_begin_i = static_cast<::vl::vint>(1);
			auto __vwsn_for_end_i = ::vl::__vwsn::This(xs.Obj())->GetCount();
			auto i = __vwsn_for_begin_i;
			while ((i <= __vwsn_for_end_i))
			{
				{
					GLOBAL_NAME CheckValue(::vl::__vwsn::Unbox<::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue>>(::vl::__vwsn::This(xs.Obj())->Get(::vl::__vwsn::Box(i))), (i == static_cast<::vl::vint>(4)), ((::vl::WString::Unmanaged(L"xsService[") + ::vl::__vwsn::ToString(i)) + ::vl::WString::Unmanaged(L"]")));
				}
				(i = (i + static_cast<::vl::vint>(1)));
			}
		}
	}

	void Rpc_CollectionDict_Interface_InByval_OutByval::serviceMain(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto serviceObj = ::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IService>(new ::vl_workflow_global::__vwsnc2_Rpc_CollectionDict_Interface_InByval_OutByval_serviceMain__RpcCollectionDict_Interface_InByval_OutByval_IService());
		::vl::__vwsn::This(lc)->RegisterService(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IService"), ::vl::Ptr<::vl::reflection::IDescriptable>(serviceObj));
	}

	::vl::WString Rpc_CollectionDict_Interface_InByval_OutByval::Print(::vl::Ptr<::vl::reflection::description::IValueDictionary> xs)
	{
		auto result = ::vl::WString::Unmanaged(L"");
		{
			auto __vwsn_for_begin_key = static_cast<::vl::vint>(1);
			auto __vwsn_for_end_key = ::vl::__vwsn::This(xs.Obj())->GetCount();
			auto key = __vwsn_for_begin_key;
			while ((key <= __vwsn_for_end_key))
			{
				{
					(result = (((((::vl::WString::Unmanaged(L"") + result) + ::vl::WString::Unmanaged(L"")) + ::vl::__vwsn::ToString(key)) + ::vl::WString::Unmanaged(L"")) + ::vl::__vwsn::This(::vl::__vwsn::Unbox<::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IValue>>(::vl::__vwsn::This(xs.Obj())->Get(::vl::__vwsn::Box(key))).Obj())->GetValue()));
				}
				(key = (key + static_cast<::vl::vint>(1)));
			}
		}
		return result;
	}

	::vl::WString Rpc_CollectionDict_Interface_InByval_OutByval::clientMain(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto xsOrigin = ::vl::reflection::description::IValueDictionary::Create();
		::vl::__vwsn::This(xsOrigin.Obj())->Set(::vl::__vwsn::Box(static_cast<::vl::vint>(1)), ::vl::__vwsn::Box(GLOBAL_NAME MakeValue(::vl::WString::Unmanaged(L"A"))));
		::vl::__vwsn::This(xsOrigin.Obj())->Set(::vl::__vwsn::Box(static_cast<::vl::vint>(2)), ::vl::__vwsn::Box(GLOBAL_NAME MakeValue(::vl::WString::Unmanaged(L"B"))));
		::vl::__vwsn::This(xsOrigin.Obj())->Set(::vl::__vwsn::Box(static_cast<::vl::vint>(3)), ::vl::__vwsn::Box(GLOBAL_NAME MakeValue(::vl::WString::Unmanaged(L"C"))));
		auto service = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcCollectionDict::Interface::InByval::OutByval::IService>(::vl::__vwsn::This(lc)->RequestService(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IService")).Obj()));
		auto xs = ::vl::__vwsn::This(service.Obj())->DoList(xsOrigin);
		auto xsObj = ::vl::__vwsn::Box(xs);
		if ((xs.Obj() == xsOrigin.Obj()))
		{
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Return value xs should be a copied local object in clientMain"));
		}
		if (static_cast<bool>(::vl::__vwsn::UnboxWeak<::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>>(xsObj)))
		{
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Return value xs should be a copied local object in clientMain"));
		}
		auto xsClient = xs;
		::vl::__vwsn::This(xs.Obj())->Set(::vl::__vwsn::Box(static_cast<::vl::vint>(5)), ::vl::__vwsn::Box(GLOBAL_NAME MakeValue(::vl::WString::Unmanaged(L"E"))));
		GLOBAL_NAME CheckServiceItems(GLOBAL_NAME xsService);
		GLOBAL_NAME CheckClientItems(xsClient);
		return ((((::vl::WString::Unmanaged(L"[") + GLOBAL_NAME Print(xsOrigin)) + ::vl::WString::Unmanaged(L"]")) + ((::vl::WString::Unmanaged(L"[") + GLOBAL_NAME Print(GLOBAL_NAME xsService)) + ::vl::WString::Unmanaged(L"]"))) + ((::vl::WString::Unmanaged(L"[") + GLOBAL_NAME Print(xsClient)) + ::vl::WString::Unmanaged(L"]")));
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> Rpc_CollectionDict_Interface_InByval_OutByval::rpc_GetIds()
	{
		auto result = ::vl::reflection::description::IValueDictionary::Create();
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IService")), ::vl::__vwsn::Box(static_cast<::vl::vint>(1)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IValue.GetValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(2)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcCollectionDict::Interface::InByval::OutByval::IService.DoList")), ::vl::__vwsn::Box(static_cast<::vl::vint>(3)));
		return result;
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> Rpc_CollectionDict_Interface_InByval_OutByval::rpc_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectOps>(new ::vl_workflow_global::__vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(lc));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> Rpc_CollectionDict_Interface_InByval_OutByval::rpc_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps>(new ::vl_workflow_global::__vwsnc4_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(lc));
	}

	::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IValue> Rpc_CollectionDict_Interface_InByval_OutByval::rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto proxyRef = ::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetController())->RequestService(GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IValue);
		auto proxy = ::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IValue>(new ::vl_workflow_global::__vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue(lc, proxyRef));
		return proxy;
	}

	::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IService> Rpc_CollectionDict_Interface_InByval_OutByval::rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto proxyRef = ::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetController())->RequestService(GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IService);
		auto proxy = ::vl::Ptr<::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IService>(new ::vl_workflow_global::__vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService(lc, proxyRef));
		return proxy;
	}

	::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> Rpc_CollectionDict_Interface_InByval_OutByval::rpcwrapper_Create(::vl::vint typeId, ::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		{
			auto __vwsn_switch_4 = typeId;
			if ((__vwsn_switch_4 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IValue))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue(lc));
			}
			else if ((__vwsn_switch_4 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IService))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService(lc));
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id for wrapper creation."));
		}
	}

	Rpc_CollectionDict_Interface_InByval_OutByval& Rpc_CollectionDict_Interface_InByval_OutByval::Instance()
	{
		return Getvl_workflow_global_Rpc_CollectionDict_Interface_InByval_OutByval().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc1_Rpc_CollectionDict_Interface_InByval_OutByval_MakeValue__RpcCollectionDict_Interface_InByval_OutByval_IValue::__vwsnc1_Rpc_CollectionDict_Interface_InByval_OutByval_MakeValue__RpcCollectionDict_Interface_InByval_OutByval_IValue(::vl::WString __vwsnctor_value)
		:value(__vwsnctor_value)
	{
	}

	::vl::WString __vwsnc1_Rpc_CollectionDict_Interface_InByval_OutByval_MakeValue__RpcCollectionDict_Interface_InByval_OutByval_IValue::GetValue()
	{
		return value;
	}

	//-------------------------------------------------------------------

	__vwsnc2_Rpc_CollectionDict_Interface_InByval_OutByval_serviceMain__RpcCollectionDict_Interface_InByval_OutByval_IService::__vwsnc2_Rpc_CollectionDict_Interface_InByval_OutByval_serviceMain__RpcCollectionDict_Interface_InByval_OutByval_IService()
	{
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> __vwsnc2_Rpc_CollectionDict_Interface_InByval_OutByval_serviceMain__RpcCollectionDict_Interface_InByval_OutByval_IService::DoList(::vl::Ptr<::vl::reflection::description::IValueDictionary> xs)
	{
		auto xsObj = ::vl::__vwsn::Box(xs);
		if (static_cast<bool>(::vl::__vwsn::UnboxWeak<::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>>(xsObj)))
		{
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Parameter xs should be a copied local object in serviceMain"));
		}
		(GLOBAL_NAME xsService = xs);
		::vl::__vwsn::This(xs.Obj())->Set(::vl::__vwsn::Box(static_cast<::vl::vint>(4)), ::vl::__vwsn::Box(GLOBAL_NAME MakeValue(::vl::WString::Unmanaged(L"D"))));
		return xs;
	}

	//-------------------------------------------------------------------

	__vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::__vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
		this->_holds = ::vl::reflection::description::IValueDictionary::Create();
		this->_services = ::vl::reflection::description::IValueDictionary::Create();
	}

	::vl::reflection::description::Value __vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		{
			auto __vwsn_switch_0 = methodId;
			if ((__vwsn_switch_0 == GLOBAL_NAME rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IValue_GetValue))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcCollectionDict::Interface::InByval::OutByval::IValue>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->GetValue()), _lc);
			}
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IService_DoList))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcCollectionDict::Interface::InByval::OutByval::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->DoList(::vl::__vwsn::Unbox<::vl::Ptr<::vl::reflection::description::IValueDictionary>>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC method id."));
		}
	}

	::vl::Ptr<::vl::reflection::description::IAsync> __vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethodAsync(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"InvokeMethodAsync is not supported."));
	}

	void __vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold)
	{
		if (hold)
		{
			::vl::__vwsn::This(_holds.Obj())->Set(::vl::__vwsn::Box(ref), ::vl::__vwsn::Box(::vl::__vwsn::This(_lc)->RefToPtr(ref)));
		}
		else
		{
			::vl::__vwsn::This(_holds.Obj())->Remove(::vl::__vwsn::Box(ref));
		}
	}

	void __vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service)
	{
		{
			auto __vwsn_switch_1 = typeId;
			if ((__vwsn_switch_1 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IValue))
			{
				if ((! static_cast<bool>(service)))
				{
					::vl::__vwsn::This(_services.Obj())->Remove(::vl::__vwsn::Box(typeId));
				}
				else
				{
					::vl::__vwsn::This(_services.Obj())->Set(::vl::__vwsn::Box(typeId), ::vl::__vwsn::Box(service));
				}
				return;
			}
			else if ((__vwsn_switch_1 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IService))
			{
				if ((! static_cast<bool>(service)))
				{
					::vl::__vwsn::This(_services.Obj())->Remove(::vl::__vwsn::Box(typeId));
				}
				else
				{
					::vl::__vwsn::This(_services.Obj())->Set(::vl::__vwsn::Box(typeId), ::vl::__vwsn::Box(service));
				}
				return;
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id."));
		}
	}

	::vl::rpc_controller::RpcObjectReference __vwsnc3_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::RequestService(::vl::vint typeId)
	{
		{
			auto __vwsn_switch_2 = typeId;
			if ((__vwsn_switch_2 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IValue))
			{
				return ::vl::__vwsn::This(_lc)->PtrToRef(::vl::__vwsn::Unbox<::vl::Ptr<::vl::reflection::IDescriptable>>(::vl::__vwsn::This(_services.Obj())->Get(::vl::__vwsn::Box(typeId))));
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpctype_RpcCollectionDict__Interface__InByval__OutByval__IService))
			{
				return ::vl::__vwsn::This(_lc)->PtrToRef(::vl::__vwsn::Unbox<::vl::Ptr<::vl::reflection::IDescriptable>>(::vl::__vwsn::This(_services.Obj())->Get(::vl::__vwsn::Box(typeId))));
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id."));
		}
	}

	//-------------------------------------------------------------------

	__vwsnc4_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::__vwsnc4_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	void __vwsnc4_Rpc_CollectionDict_Interface_InByval_OutByval_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		{
			auto __vwsn_switch_3 = eventId;
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC event id."));
		}
	}

	//-------------------------------------------------------------------

	__vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue::__vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
	}

	void __vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifeCycle*>(nullptr));
	}

	__vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue::~__vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->ReleaseRemoteObject(_ref);
		}
	}

	::vl::WString __vwsnc5_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IValue__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IValue::GetValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		return ::vl::__vwsn::Unbox<::vl::WString>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IValue_GetValue, arguments), _lc));
	}

	//-------------------------------------------------------------------

	__vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService::__vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
	}

	void __vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifeCycle*>(nullptr));
	}

	__vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService::~__vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->ReleaseRemoteObject(_ref);
		}
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> __vwsnc6_Rpc_CollectionDict_Interface_InByval_OutByval_rpcwrapper_RpcCollectionDict__Interface__InByval__OutByval__IService__RpcCollectionDict_Interface_InByval_OutByval_IRpcWrapper_IService::DoList(::vl::Ptr<::vl::reflection::description::IValueDictionary> xs)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(xs), _lc));
		return ::vl::__vwsn::Unbox<::vl::Ptr<::vl::reflection::description::IValueDictionary>>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcCollectionDict__Interface__InByval__OutByval__IService_DoList, arguments), _lc));
	}

}

/***********************************************************************
Class (::RpcCollectionDict::Interface::InByval::OutByval::IService)
***********************************************************************/

namespace RpcCollectionDict
{
	namespace Interface
	{
		namespace InByval
		{
			namespace OutByval
			{
/***********************************************************************
Class (::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IService)
***********************************************************************/

/***********************************************************************
Class (::RpcCollectionDict::Interface::InByval::OutByval::IValue)
***********************************************************************/

/***********************************************************************
Class (::RpcCollectionDict::Interface::InByval::OutByval::IRpcWrapper_IValue)
***********************************************************************/

			}
		}
	}
}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
