/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/Collection_Interface_PropDefault.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_COLLECTION_INTERFACE_PROPDEFAULT
#define VCZH_WORKFLOW_COMPILER_GENERATED_COLLECTION_INTERFACE_PROPDEFAULT

#include "../Source/CppTypes.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	class __vwsnc1_Rpc_Collection_Interface_PropDefault_MakeValue__RpcCollection_Interface_PropDefault_IValue;
	class __vwsnc2_Rpc_Collection_Interface_PropDefault_serviceMain__RpcCollection_Interface_PropDefault_IService;
	class __vwsnc3_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps;
	class __vwsnc4_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps;
	class __vwsnc5_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IValue__RpcCollection_Interface_PropDefault_IRpcWrapper_IValue;
	class __vwsnc6_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IService__RpcCollection_Interface_PropDefault_IRpcWrapper_IService;
}

namespace RpcCollection
{
	namespace Interface
	{
		namespace PropDefault
		{
			class IService;
			class IRpcWrapper_IService;
			class IValue;
			class IRpcWrapper_IValue;

			class IService : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<IService>
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IService>;
#endif
			public:
				virtual ::vl::Ptr<::vl::reflection::description::IValueList> GetList() = 0;
				virtual void SetList(::vl::Ptr<::vl::reflection::description::IValueList> __vwsn_value_) = 0;
			};

			class IRpcWrapper_IService : public virtual ::RpcCollection::Interface::PropDefault::IService, public virtual ::vl::rpc_controller::IRpcWrapperBase, public ::vl::reflection::Description<IRpcWrapper_IService>
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IRpcWrapper_IService>;
#endif
			};

			class IValue : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<IValue>
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IValue>;
#endif
			public:
				virtual ::vl::WString GetValue() = 0;
			};

			class IRpcWrapper_IValue : public virtual ::RpcCollection::Interface::PropDefault::IValue, public virtual ::vl::rpc_controller::IRpcWrapperBase, public ::vl::reflection::Description<IRpcWrapper_IValue>
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IRpcWrapper_IValue>;
#endif
			};

		}
	}
}
/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class Rpc_Collection_Interface_PropDefault
	{
	public:

		::vl::Ptr<::vl::reflection::description::IValueList> xsService;
		::vl::vint rpctype_RpcCollection__Interface__PropDefault__IValue = 0;
		::vl::vint rpctype_RpcCollection__Interface__PropDefault__IService = 0;
		::vl::vint rpcmethod_RpcCollection__Interface__PropDefault__IValue_GetValue = 0;
		::vl::vint rpcmethod_RpcCollection__Interface__PropDefault__IService_GetList = 0;
		::vl::vint rpcmethod_RpcCollection__Interface__PropDefault__IService_SetList = 0;

		::vl::Ptr<::RpcCollection::Interface::PropDefault::IValue> MakeValue(::vl::vint value);
		::vl::Ptr<::RpcCollection::Interface::PropDefault::IValue> MakeValue(const ::vl::WString& value);
		void CheckValue(::vl::Ptr<::RpcCollection::Interface::PropDefault::IValue> value, bool shouldBeWrapper, const ::vl::WString& name);
		void CheckServiceItems(::vl::Ptr<::vl::reflection::description::IValueList> xs);
		void CheckClientItems(::vl::Ptr<::vl::reflection::description::IValueList> xs);
		void serviceMain(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::WString Print(::vl::Ptr<::vl::reflection::description::IValueList> xs);
		::vl::WString clientMain(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::Ptr<::vl::reflection::description::IValueDictionary> rpc_GetIds();
		bool rpcwrapper_IsInterfaceTypeId(::vl::vint typeId);
		bool rpcwrapper_IsCtorInterfaceTypeId(::vl::vint typeId);
		::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> rpc_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> rpc_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::Ptr<::RpcCollection::Interface::PropDefault::IRpcWrapper_IValue> rpcwrapper_RpcCollection__Interface__PropDefault__IValue(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::Ptr<::RpcCollection::Interface::PropDefault::IRpcWrapper_IService> rpcwrapper_RpcCollection__Interface__PropDefault__IService(::vl::rpc_controller::IRpcLifeCycle* lc);
		::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> rpcwrapper_Create(::vl::vint typeId, ::vl::rpc_controller::IRpcLifeCycle* lc);

		static Rpc_Collection_Interface_PropDefault& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	class __vwsnc1_Rpc_Collection_Interface_PropDefault_MakeValue__RpcCollection_Interface_PropDefault_IValue : public ::vl::Object, public virtual ::RpcCollection::Interface::PropDefault::IValue
	{
	public:
		::vl::WString value;

		__vwsnc1_Rpc_Collection_Interface_PropDefault_MakeValue__RpcCollection_Interface_PropDefault_IValue(::vl::WString __vwsnctor_value);

		::vl::WString GetValue() override;
	};

	class __vwsnc2_Rpc_Collection_Interface_PropDefault_serviceMain__RpcCollection_Interface_PropDefault_IService : public ::vl::Object, public virtual ::RpcCollection::Interface::PropDefault::IService
	{
	public:
		__vwsnc2_Rpc_Collection_Interface_PropDefault_serviceMain__RpcCollection_Interface_PropDefault_IService();

		::vl::Ptr<::vl::reflection::description::IValueList> _List;
		::vl::Ptr<::vl::reflection::description::IValueList> GetList() override;
		void SetList(::vl::Ptr<::vl::reflection::description::IValueList> xs) override;
	};

	class __vwsnc3_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectOps
	{
	public:
		__vwsnc3_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifeCycle* _lc = nullptr;
		::vl::Ptr<::vl::reflection::description::IValueDictionary> _services;
		::vl::reflection::description::Value InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
		::vl::Ptr<::vl::reflection::description::IAsync> InvokeMethodAsync(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
		void ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold) override;
		void RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service) override;
		::vl::rpc_controller::RpcObjectReference RequestService(::vl::vint typeId) override;
	};

	class __vwsnc4_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectEventOps
	{
	public:
		__vwsnc4_Rpc_Collection_Interface_PropDefault_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifeCycle* _lc = nullptr;
		void InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
	};

	class __vwsnc5_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IValue__RpcCollection_Interface_PropDefault_IRpcWrapper_IValue : public ::vl::Object, public virtual ::RpcCollection::Interface::PropDefault::IRpcWrapper_IValue
	{
	public:
		__vwsnc5_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IValue__RpcCollection_Interface_PropDefault_IRpcWrapper_IValue(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef);

		::vl::rpc_controller::IRpcLifeCycle* _lc = nullptr;
		::vl::rpc_controller::RpcObjectReference _ref;
		void DisconnectFromLifecycle() override;
		~__vwsnc5_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IValue__RpcCollection_Interface_PropDefault_IRpcWrapper_IValue();
		::vl::WString GetValue() override;
	};

	class __vwsnc6_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IService__RpcCollection_Interface_PropDefault_IRpcWrapper_IService : public ::vl::Object, public virtual ::RpcCollection::Interface::PropDefault::IRpcWrapper_IService
	{
	public:
		__vwsnc6_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IService__RpcCollection_Interface_PropDefault_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef);

		::vl::rpc_controller::IRpcLifeCycle* _lc = nullptr;
		::vl::rpc_controller::RpcObjectReference _ref;
		void DisconnectFromLifecycle() override;
		~__vwsnc6_Rpc_Collection_Interface_PropDefault_rpcwrapper_RpcCollection__Interface__PropDefault__IService__RpcCollection_Interface_PropDefault_IRpcWrapper_IService();
		::vl::Ptr<::vl::reflection::description::IValueList> GetList() override;
		void SetList(::vl::Ptr<::vl::reflection::description::IValueList> __vwsn_value_) override;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
