/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/Inheritance.txt; ../Resources/Rpc/Inheritance_Test.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_INHERITANCEREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_INHERITANCEREFLECTION

#include "Inheritance.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::RpcInheritance::IDerived)
			DECL_TYPE_INFO(::RpcInheritance::IOne)
			DECL_TYPE_INFO(::RpcInheritance::IRpcWrapper_IDerived)
			DECL_TYPE_INFO(::RpcInheritance::IRpcWrapper_IOne)
			DECL_TYPE_INFO(::RpcInheritance::IRpcWrapper_IService)
			DECL_TYPE_INFO(::RpcInheritance::IRpcWrapper_ITwo)
			DECL_TYPE_INFO(::RpcInheritance::IRpcWrapper_IValue)
			DECL_TYPE_INFO(::RpcInheritance::IService)
			DECL_TYPE_INFO(::RpcInheritance::ITwo)
			DECL_TYPE_INFO(::RpcInheritance::IValue)
			DECL_TYPE_INFO(::rpcops_IOps_Rpc_Inheritance)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcInheritance::IService)
				::vl::Ptr<::RpcInheritance::IDerived> CreateDerived() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(CreateDerived);
				}
				::vl::Ptr<::RpcInheritance::IOne> CreateOne() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(CreateOne);
				}
				::vl::Ptr<::RpcInheritance::ITwo> CreateTwo() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(CreateTwo);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IService)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcInheritance::IValue)
				::vl::WString GetValue() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetValue);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IValue)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::rpcops_IOps_Rpc_Inheritance)
				void InvokeEvent_RpcInheritance__IOne_CrashAtServer(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeEvent_RpcInheritance__IOne_CrashAtServer, ref);
				}
				void InvokeEvent_RpcInheritance__ITwo_CrashAtClient(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeEvent_RpcInheritance__ITwo_CrashAtClient, ref);
				}
				void InvokeEvent_RpcInheritance__IValue_ValueChanged(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeEvent_RpcInheritance__IValue_ValueChanged, ref);
				}
				::vl::WString InvokeMethod_RpcInheritance__IDerived_GuardCrashAtClient(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IDerived_GuardCrashAtClient, ref);
				}
				void InvokeMethod_RpcInheritance__IDerived_SetDerivedValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IDerived_SetDerivedValue, ref);
				}
				void InvokeMethod_RpcInheritance__IOne_SetOneValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IOne_SetOneValue, ref);
				}
				::vl::Ptr<::RpcInheritance::IDerived> InvokeMethod_RpcInheritance__IService_CreateDerived(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IService_CreateDerived, ref);
				}
				::vl::Ptr<::RpcInheritance::IOne> InvokeMethod_RpcInheritance__IService_CreateOne(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IService_CreateOne, ref);
				}
				::vl::Ptr<::RpcInheritance::ITwo> InvokeMethod_RpcInheritance__IService_CreateTwo(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IService_CreateTwo, ref);
				}
				void InvokeMethod_RpcInheritance__ITwo_SetTwoValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcInheritance__ITwo_SetTwoValue, ref);
				}
				::vl::WString InvokeMethod_RpcInheritance__IValue_GetValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcInheritance__IValue_GetValue, ref);
				}
			END_INTERFACE_PROXY(::rpcops_IOps_Rpc_Inheritance)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IOne, ::RpcInheritance::IValue)
				void SetOneValue() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(SetOneValue);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IOne)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IRpcWrapper_IOne, ::RpcInheritance::IOne, ::vl::rpc_controller::IRpcWrapperBase)
				void _rpcInvalidate_Value() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(_rpcInvalidate_Value);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IRpcWrapper_IOne)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IRpcWrapper_IService, ::RpcInheritance::IService, ::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_PROXY(::RpcInheritance::IRpcWrapper_IService)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IRpcWrapper_IValue, ::RpcInheritance::IValue, ::vl::rpc_controller::IRpcWrapperBase)
				void _rpcInvalidate_Value() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(_rpcInvalidate_Value);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IRpcWrapper_IValue)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::ITwo, ::RpcInheritance::IValue)
				void SetTwoValue() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(SetTwoValue);
				}
			END_INTERFACE_PROXY(::RpcInheritance::ITwo)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IDerived, ::RpcInheritance::IOne, ::RpcInheritance::ITwo)
				::vl::WString GuardCrashAtClient() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GuardCrashAtClient);
				}
				void SetDerivedValue() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(SetDerivedValue);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IDerived)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IRpcWrapper_IDerived, ::RpcInheritance::IDerived, ::vl::rpc_controller::IRpcWrapperBase)
				void _rpcInvalidate_Value() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(_rpcInvalidate_Value);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IRpcWrapper_IDerived)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcInheritance::IRpcWrapper_ITwo, ::RpcInheritance::ITwo, ::vl::rpc_controller::IRpcWrapperBase)
				void _rpcInvalidate_Value() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(_rpcInvalidate_Value);
				}
			END_INTERFACE_PROXY(::RpcInheritance::IRpcWrapper_ITwo)
#endif
#endif

			extern bool LoadRpc_InheritanceTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
