/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/Nullable.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "Nullable.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, NullableReflection.h) */
#include "NullableReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Rpc_Nullable::
#define GLOBAL_NAME ::vl_workflow_global::Rpc_Nullable::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Rpc_Nullable::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_Nullable)
	vl_workflow_global::Rpc_Nullable instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Unmanaged(L"");
		instance.rpctype_RpcNullable__IValue = static_cast<::vl::vint>(0);
		instance.rpctype_RpcNullable__IService = static_cast<::vl::vint>(1);
		instance.rpcmethod_RpcNullable__IValue_GetValue = static_cast<::vl::vint>(2);
		instance.rpcmethod_RpcNullable__IService_Print = static_cast<::vl::vint>(3);
	FINALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Empty;
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_Nullable)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	void Rpc_Nullable::serviceMain(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto serviceObj = ::vl::Ptr<::RpcNullable::IService>(new ::vl_workflow_global::__vwsnc1_Rpc_Nullable_serviceMain__RpcNullable_IService());
		::vl::__vwsn::This(lc)->RegisterService(::vl::WString::Unmanaged(L"RpcNullable::IService"), ::vl::Ptr<::vl::reflection::IDescriptable>(serviceObj));
	}

	::vl::WString Rpc_Nullable::clientMain(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		auto service = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcNullable::IService>(::vl::__vwsn::This(lc)->RequestService(::vl::WString::Unmanaged(L"RpcNullable::IService")).Obj()));
		(GLOBAL_NAME s = (GLOBAL_NAME s + ::vl::__vwsn::This(service.Obj())->Print(::vl::Nullable<::vl::WString>(::vl::WString::Unmanaged(L"abc")), ::vl::Ptr<::RpcNullable::IValue>())));
		auto value = ::vl::Ptr<::RpcNullable::IValue>(new ::vl_workflow_global::__vwsnc2_Rpc_Nullable_clientMain__RpcNullable_IValue());
		(GLOBAL_NAME s = (GLOBAL_NAME s + ::vl::__vwsn::This(service.Obj())->Print(::vl::Nullable<::vl::WString>(), value)));
		return GLOBAL_NAME s;
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> Rpc_Nullable::rpc_GetIds()
	{
		auto result = ::vl::reflection::description::IValueDictionary::Create();
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcNullable::IValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcNullable::IService")), ::vl::__vwsn::Box(static_cast<::vl::vint>(1)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcNullable::IValue.GetValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(2)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcNullable::IService.Print")), ::vl::__vwsn::Box(static_cast<::vl::vint>(3)));
		return result;
	}

	bool Rpc_Nullable::rpcwrapper_IsInterfaceTypeId(::vl::vint typeId)
	{
		if (((typeId >= static_cast<::vl::vint>(-7)) && (typeId <= static_cast<::vl::vint>(-1))))
			return true;
		{
			auto __vwsn_switch_0 = typeId;
			if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcNullable__IValue))
				return true;
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcNullable__IService))
				return true;
			else
				return false;
		}
	}

	bool Rpc_Nullable::rpcwrapper_IsCtorInterfaceTypeId(::vl::vint typeId)
	{
		{
			auto __vwsn_switch_1 = typeId;
			if ((__vwsn_switch_1 == GLOBAL_NAME rpctype_RpcNullable__IService))
				return true;
			else
				return false;
		}
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> Rpc_Nullable::rpc_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectOps>(new ::vl_workflow_global::__vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(lc));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> Rpc_Nullable::rpc_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps>(new ::vl_workflow_global::__vwsnc4_Rpc_Nullable_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(lc));
	}

	::vl::Ptr<::RpcNullable::IRpcWrapper_IValue> Rpc_Nullable::rpcwrapper_RpcNullable__IValue(::vl::rpc_controller::IRpcLifeCycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef)
	{
		auto proxy = ::vl::Ptr<::RpcNullable::IRpcWrapper_IValue>(new ::vl_workflow_global::__vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue(lc, proxyRef));
		return proxy;
	}

	::vl::Ptr<::RpcNullable::IRpcWrapper_IService> Rpc_Nullable::rpcwrapper_RpcNullable__IService(::vl::rpc_controller::IRpcLifeCycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef)
	{
		auto proxy = ::vl::Ptr<::RpcNullable::IRpcWrapper_IService>(new ::vl_workflow_global::__vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService(lc, proxyRef));
		return proxy;
	}

	::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> Rpc_Nullable::rpcwrapper_Create(::vl::rpc_controller::RpcObjectReference ref, ::vl::rpc_controller::IRpcLifeCycle* lc)
	{
		{
			auto __vwsn_switch_4 = ref.typeId;
			if ((__vwsn_switch_4 == GLOBAL_NAME rpctype_RpcNullable__IValue))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcNullable__IValue(lc, ref));
			}
			else if ((__vwsn_switch_4 == GLOBAL_NAME rpctype_RpcNullable__IService))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcNullable__IService(lc, ref));
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id for wrapper creation."));
		}
	}

	Rpc_Nullable& Rpc_Nullable::Instance()
	{
		return Getvl_workflow_global_Rpc_Nullable().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc1_Rpc_Nullable_serviceMain__RpcNullable_IService::__vwsnc1_Rpc_Nullable_serviceMain__RpcNullable_IService()
	{
	}

	::vl::WString __vwsnc1_Rpc_Nullable_serviceMain__RpcNullable_IService::Print(const ::vl::Nullable<::vl::WString>& value, ::vl::Ptr<::RpcNullable::IValue> v)
	{
		auto nullableText = ((! static_cast<bool>(value)) ? ::vl::WString::Unmanaged(L"null") : value.Value());
		auto valueText = ((! static_cast<bool>(v)) ? ::vl::WString::Unmanaged(L"null") : ::vl::__vwsn::This(v.Obj())->GetValue());
		return ((((::vl::WString::Unmanaged(L"[") + nullableText) + ::vl::WString::Unmanaged(L"][")) + valueText) + ::vl::WString::Unmanaged(L"]"));
	}

	//-------------------------------------------------------------------

	__vwsnc2_Rpc_Nullable_clientMain__RpcNullable_IValue::__vwsnc2_Rpc_Nullable_clientMain__RpcNullable_IValue()
	{
	}

	::vl::WString __vwsnc2_Rpc_Nullable_clientMain__RpcNullable_IValue::GetValue()
	{
		return ::vl::WString::Unmanaged(L"def");
	}

	//-------------------------------------------------------------------

	__vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::__vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	::vl::reflection::description::Value __vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		{
			auto __vwsn_switch_2 = methodId;
			if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcNullable__IValue_GetValue))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcNullable::IValue>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->GetValue()), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcNullable__IService_Print))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcNullable::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->Print(::vl::__vwsn::Unbox<::vl::Nullable<::vl::WString>>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)), ::vl::__vwsn::Unbox<::vl::Ptr<::RpcNullable::IValue>>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(1))), _lc)))), _lc);
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC method id."));
		}
	}

	::vl::Ptr<::vl::reflection::description::IAsync> __vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethodAsync(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"InvokeMethodAsync is not supported."));
	}

	void __vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold)
	{
		if (hold)
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->AcquireRemoteObject(ref);
		}
		else
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->ReleaseRemoteObject(ref);
		}
	}

	void __vwsnc3_Rpc_Nullable_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service)
	{
		{
			if (GLOBAL_NAME rpcwrapper_IsCtorInterfaceTypeId(typeId))
			{
				::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->RegisterService(typeId, ::vl::__vwsn::This(_lc)->PtrToRef(service));
			}
			else
			{
				if (GLOBAL_NAME rpcwrapper_IsInterfaceTypeId(typeId))
				{
					throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC service type id is not an @rpc:Ctor interface."));
				}
				else
				{
					throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC service type id does not exist."));
				}
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsnc4_Rpc_Nullable_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::__vwsnc4_Rpc_Nullable_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	void __vwsnc4_Rpc_Nullable_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->SetEventSuppressedFlag(ref, eventId, true);
		{
			auto __vwsnb_0 = [&]()
			{
				::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->SetEventSuppressedFlag(ref, eventId, false);
			}
			;
			::vl::__vwsn::RunOnExit<::std::remove_cvref_t<decltype(__vwsnb_0)>> __vwsnb_0_dtor(&__vwsnb_0);
			try
			{
				{
					auto __vwsn_switch_3 = eventId;
					throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC event id."));
				}
			}
			catch(const ::vl::Exception&)
			{
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue::__vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->__vwsn_Cached_ = ::vl::WString::Unmanaged(L"");
		this->__vwsn_Available_ = false;
	}

	void __vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifeCycle*>(nullptr));
	}

	__vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue::~__vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->ReleaseRemoteObject(_ref);
		}
	}

	::vl::WString __vwsnc5_Rpc_Nullable_rpcwrapper_RpcNullable__IValue__RpcNullable_IRpcWrapper_IValue::GetValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		if (__vwsn_Available_)
		{
			return __vwsn_Cached_;
		}
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		(__vwsn_Cached_ = ::vl::__vwsn::Unbox<::vl::WString>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcNullable__IValue_GetValue, arguments), _lc)));
		(__vwsn_Available_ = true);
		return __vwsn_Cached_;
	}

	//-------------------------------------------------------------------

	__vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService::__vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifeCycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
	}

	void __vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifeCycle*>(nullptr));
	}

	__vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService::~__vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->ReleaseRemoteObject(_ref);
		}
	}

	::vl::WString __vwsnc6_Rpc_Nullable_rpcwrapper_RpcNullable__IService__RpcNullable_IRpcWrapper_IService::Print(const ::vl::Nullable<::vl::WString>& value, ::vl::Ptr<::RpcNullable::IValue> v)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(2));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(1), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(v), _lc));
		return ::vl::__vwsn::Unbox<::vl::WString>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcNullable__IService_Print, arguments), _lc));
	}

}

/***********************************************************************
Class (::RpcNullable::IService)
***********************************************************************/

namespace RpcNullable
{
/***********************************************************************
Class (::RpcNullable::IRpcWrapper_IService)
***********************************************************************/

/***********************************************************************
Class (::RpcNullable::IValue)
***********************************************************************/

/***********************************************************************
Class (::RpcNullable::IRpcWrapper_IValue)
***********************************************************************/

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
