/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/PrimitiveTypes.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PrimitiveTypes.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, PrimitiveTypesReflection.h) */
#include "PrimitiveTypesReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Rpc_PrimitiveTypes::
#define GLOBAL_NAME ::vl_workflow_global::Rpc_PrimitiveTypes::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Rpc_PrimitiveTypes::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_PrimitiveTypes)
	vl_workflow_global::Rpc_PrimitiveTypes instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.rpctype_RpcPrimitiveTest__IService = static_cast<::vl::vint>(0);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessInt = static_cast<::vl::vint>(1);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessUInt = static_cast<::vl::vint>(2);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessFloat = static_cast<::vl::vint>(3);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessDouble = static_cast<::vl::vint>(4);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessString = static_cast<::vl::vint>(5);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessBool = static_cast<::vl::vint>(6);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessEnum = static_cast<::vl::vint>(7);
		instance.rpcmethod_RpcPrimitiveTest__IService_ProcessStruct = static_cast<::vl::vint>(8);
	FINALIZE_GLOBAL_STORAGE_CLASS

END_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_PrimitiveTypes)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	void Rpc_PrimitiveTypes::serviceMain(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		auto service = ::vl::Ptr<::RpcPrimitiveTest::IService>(new ::vl_workflow_global::__vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService());
		::vl::__vwsn::This(lc)->RegisterService(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService"), ::vl::Ptr<::vl::reflection::IDescriptable>(service));
	}

	::vl::WString Rpc_PrimitiveTypes::clientMain(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		auto obj = ::vl::__vwsn::This(lc)->RequestService(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService"));
		auto service = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(obj.Obj()));
		auto result = ::vl::WString::Unmanaged(L"");
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::vl::__vwsn::This(service.Obj())->ProcessInt(static_cast<::vl::vint>(5)))) + ::vl::WString::Unmanaged(L"]")));
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::vl::__vwsn::This(service.Obj())->ProcessUInt(static_cast<::vl::vuint>(static_cast<::vl::vint>(10))))) + ::vl::WString::Unmanaged(L"]")));
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::vl::__vwsn::This(service.Obj())->ProcessFloat(static_cast<float>(static_cast<double>(1.5))))) + ::vl::WString::Unmanaged(L"]")));
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::vl::__vwsn::This(service.Obj())->ProcessDouble(static_cast<double>(2.75)))) + ::vl::WString::Unmanaged(L"]")));
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::This(service.Obj())->ProcessString(::vl::WString::Unmanaged(L"Hi"))) + ::vl::WString::Unmanaged(L"]")));
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(::vl::__vwsn::This(service.Obj())->ProcessBool(true))) + ::vl::WString::Unmanaged(L"]")));
		auto season = ::vl::__vwsn::This(service.Obj())->ProcessEnum(::RpcPrimitiveTest::Season::Autumn);
		(result = (((result + ::vl::WString::Unmanaged(L"[")) + ((season == ::RpcPrimitiveTest::Season::Autumn) ? ::vl::WString::Unmanaged(L"Autumn") : ::vl::WString::Unmanaged(L"Wrong"))) + ::vl::WString::Unmanaged(L"]")));
		auto pt = ::vl::__vwsn::This(service.Obj())->ProcessStruct([&](){ ::RpcPrimitiveTest::Point __vwsn_temp__; __vwsn_temp__.x = static_cast<::vl::vint>(3); __vwsn_temp__.y = static_cast<::vl::vint>(7); return __vwsn_temp__; }());
		(result = (((((result + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::ToString(pt.x)) + ::vl::WString::Unmanaged(L",")) + ::vl::__vwsn::ToString(pt.y)) + ::vl::WString::Unmanaged(L"]")));
		return result;
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> Rpc_PrimitiveTypes::rpc_GetIds()
	{
		auto result = ::vl::reflection::description::IValueDictionary::Create();
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService")), ::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessInt")), ::vl::__vwsn::Box(static_cast<::vl::vint>(1)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessUInt")), ::vl::__vwsn::Box(static_cast<::vl::vint>(2)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessFloat")), ::vl::__vwsn::Box(static_cast<::vl::vint>(3)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessDouble")), ::vl::__vwsn::Box(static_cast<::vl::vint>(4)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessString")), ::vl::__vwsn::Box(static_cast<::vl::vint>(5)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessBool")), ::vl::__vwsn::Box(static_cast<::vl::vint>(6)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessEnum")), ::vl::__vwsn::Box(static_cast<::vl::vint>(7)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcPrimitiveTest::IService.ProcessStruct")), ::vl::__vwsn::Box(static_cast<::vl::vint>(8)));
		return result;
	}

	bool Rpc_PrimitiveTypes::rpcwrapper_IsInterfaceTypeId(::vl::vint typeId)
	{
		if (((typeId >= static_cast<::vl::vint>(-7)) && (typeId <= static_cast<::vl::vint>(-1))))
			return true;
		{
			auto __vwsn_switch_0 = typeId;
			if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcPrimitiveTest__IService))
				return true;
			else
				return false;
		}
	}

	bool Rpc_PrimitiveTypes::rpcwrapper_IsCtorInterfaceTypeId(::vl::vint typeId)
	{
		{
			auto __vwsn_switch_1 = typeId;
			if ((__vwsn_switch_1 == GLOBAL_NAME rpctype_RpcPrimitiveTest__IService))
				return true;
			else
				return false;
		}
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> Rpc_PrimitiveTypes::rpc_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectOps>(new ::vl_workflow_global::__vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(lc));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> Rpc_PrimitiveTypes::rpc_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps>(new ::vl_workflow_global::__vwsnc3_Rpc_PrimitiveTypes_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(lc));
	}

	::vl::Ptr<::RpcPrimitiveTest::IRpcWrapper_IService> Rpc_PrimitiveTypes::rpcwrapper_RpcPrimitiveTest__IService(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef)
	{
		auto proxy = ::vl::Ptr<::RpcPrimitiveTest::IRpcWrapper_IService>(new ::vl_workflow_global::__vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService(lc, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> Rpc_PrimitiveTypes::rpcwrapper_Create(::vl::rpc_controller::RpcObjectReference ref, ::vl::rpc_controller::IRpcLifecycle* lc)
	{
		{
			auto __vwsn_switch_4 = ref.typeId;
			if ((__vwsn_switch_4 == GLOBAL_NAME rpctype_RpcPrimitiveTest__IService))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcPrimitiveTest__IService(lc, ref));
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id for wrapper creation."));
		}
	}

	Rpc_PrimitiveTypes& Rpc_PrimitiveTypes::Instance()
	{
		return Getvl_workflow_global_Rpc_PrimitiveTypes().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::__vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService()
	{
	}

	::vl::vint __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessInt(::vl::vint value)
	{
		return (value + static_cast<::vl::vint>(1));
	}

	::vl::vuint __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessUInt(::vl::vuint value)
	{
		return (value + static_cast<::vl::vuint>(static_cast<::vl::vint>(2)));
	}

	float __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessFloat(float value)
	{
		return (value + static_cast<float>(static_cast<double>(0.25)));
	}

	double __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessDouble(double value)
	{
		return (value + static_cast<double>(0.125));
	}

	::vl::WString __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessString(const ::vl::WString& value)
	{
		return (value + ::vl::WString::Unmanaged(L"!"));
	}

	bool __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessBool(bool value)
	{
		return (! value);
	}

	::RpcPrimitiveTest::Season __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessEnum(::RpcPrimitiveTest::Season value)
	{
		return value;
	}

	::RpcPrimitiveTest::Point __vwsnc1_Rpc_PrimitiveTypes_serviceMain__RpcPrimitiveTest_IService::ProcessStruct(::RpcPrimitiveTest::Point value)
	{
		auto result = [&](){ ::RpcPrimitiveTest::Point __vwsn_temp__; __vwsn_temp__.x = (value.x + static_cast<::vl::vint>(10)); __vwsn_temp__.y = (value.y + static_cast<::vl::vint>(20)); return __vwsn_temp__; }();
		return result;
	}

	//-------------------------------------------------------------------

	__vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::__vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	::vl::reflection::description::Value __vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		{
			auto __vwsn_switch_2 = methodId;
			if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessBool))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessBool(::vl::__vwsn::Unbox<bool>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessDouble))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessDouble(::vl::__vwsn::Unbox<double>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessEnum))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessEnum(::vl::__vwsn::Unbox<::RpcPrimitiveTest::Season>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessFloat))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessFloat(::vl::__vwsn::Unbox<float>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessInt))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessInt(::vl::__vwsn::Unbox<::vl::vint>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessString))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessString(::vl::__vwsn::Unbox<::vl::WString>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessStruct))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessStruct(::vl::__vwsn::Unbox<::RpcPrimitiveTest::Point>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessUInt))
			{
				auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcPrimitiveTest::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
				return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->ProcessUInt(::vl::__vwsn::Unbox<::vl::vuint>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::Unbox<::vl::reflection::description::Value>(::vl::__vwsn::This(arguments.Obj())->Get(static_cast<::vl::vint>(0))), _lc)))), _lc);
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC method id."));
		}
	}

	::vl::Ptr<::vl::reflection::description::IAsync> __vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethodAsync(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"InvokeMethodAsync is not supported."));
	}

	void __vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold)
	{
		if (hold)
		{
			::vl::__vwsn::This(_lc)->LocalObjectHold(ref, remoteClientId);
		}
		else
		{
			::vl::__vwsn::This(_lc)->LocalObjectUnhold(ref, remoteClientId);
		}
	}

	void __vwsnc2_Rpc_PrimitiveTypes_rpc_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service)
	{
		{
			if (GLOBAL_NAME rpcwrapper_IsCtorInterfaceTypeId(typeId))
			{
				::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->RegisterService(typeId, ::vl::__vwsn::This(_lc)->PtrToRef(service));
			}
			else
			{
				if (GLOBAL_NAME rpcwrapper_IsInterfaceTypeId(typeId))
				{
					throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC service type id is not an @rpc:Ctor interface."));
				}
				else
				{
					throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC service type id does not exist."));
				}
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsnc3_Rpc_PrimitiveTypes_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::__vwsnc3_Rpc_PrimitiveTypes_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	void __vwsnc3_Rpc_PrimitiveTypes_rpc_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->SetEventSuppressedFlag(ref, eventId, true);
		{
			auto __vwsnb_0 = [&]()
			{
				::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetController())->SetEventSuppressedFlag(ref, eventId, false);
			}
			;
			::vl::__vwsn::RunOnExit<::std::remove_cvref_t<decltype(__vwsnb_0)>> __vwsnb_0_dtor(&__vwsnb_0);
			try
			{
				{
					auto __vwsn_switch_3 = eventId;
					throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC event id."));
				}
			}
			catch(const ::vl::Exception&)
			{
			}
		}
	}

	//-------------------------------------------------------------------

	__vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::__vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
	}

	void __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
	}

	__vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::~__vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	bool __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessBool(bool value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<bool>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessBool, arguments), _lc));
	}

	double __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessDouble(double value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<double>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessDouble, arguments), _lc));
	}

	::RpcPrimitiveTest::Season __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessEnum(::RpcPrimitiveTest::Season value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<::RpcPrimitiveTest::Season>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessEnum, arguments), _lc));
	}

	float __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessFloat(float value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<float>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessFloat, arguments), _lc));
	}

	::vl::vint __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessInt(::vl::vint value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<::vl::vint>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessInt, arguments), _lc));
	}

	::vl::WString __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessString(const ::vl::WString& value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<::vl::WString>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessString, arguments), _lc));
	}

	::RpcPrimitiveTest::Point __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessStruct(::RpcPrimitiveTest::Point value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<::RpcPrimitiveTest::Point>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessStruct, arguments), _lc));
	}

	::vl::vuint __vwsnc4_Rpc_PrimitiveTypes_rpcwrapper_RpcPrimitiveTest__IService__RpcPrimitiveTest_IRpcWrapper_IService::ProcessUInt(::vl::vuint value)
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(1));
		::vl::__vwsn::This(arguments.Obj())->Set(static_cast<::vl::vint>(0), ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(value), _lc));
		return ::vl::__vwsn::Unbox<::vl::vuint>(::vl::rpc_controller::RpcUnboxByval(::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->InvokeMethod(_ref, GLOBAL_NAME rpcmethod_RpcPrimitiveTest__IService_ProcessUInt, arguments), _lc));
	}

}

/***********************************************************************
Class (::RpcPrimitiveTest::IService)
***********************************************************************/

namespace RpcPrimitiveTest
{
/***********************************************************************
Class (::RpcPrimitiveTest::IRpcWrapper_IService)
***********************************************************************/

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
