/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/PrimitiveTypes.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "PrimitiveTypesReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(RpcPrimitiveTest::IRpcWrapper_IService)
			IMPL_CPP_TYPE_INFO(RpcPrimitiveTest::IService)
			IMPL_CPP_TYPE_INFO(RpcPrimitiveTest::Point)
			IMPL_CPP_TYPE_INFO(RpcPrimitiveTest::Season)
			IMPL_CPP_TYPE_INFO(rpcops_IOps_Rpc_PrimitiveTypes)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_INTERFACE_MEMBER(::RpcPrimitiveTest::IRpcWrapper_IService)
				CLASS_MEMBER_BASE(::RpcPrimitiveTest::IService)
				CLASS_MEMBER_BASE(::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_MEMBER(::RpcPrimitiveTest::IRpcWrapper_IService)

			BEGIN_INTERFACE_MEMBER(::RpcPrimitiveTest::IService)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_rpc_Interface)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_rpc_Ctor)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(ProcessBool, { L"value" })
				CLASS_MEMBER_METHOD(ProcessDouble, { L"value" })
				CLASS_MEMBER_METHOD(ProcessEnum, { L"value" })
				CLASS_MEMBER_METHOD(ProcessFloat, { L"value" })
				CLASS_MEMBER_METHOD(ProcessInt, { L"value" })
				CLASS_MEMBER_METHOD(ProcessString, { L"value" })
				CLASS_MEMBER_METHOD(ProcessStruct, { L"value" })
				CLASS_MEMBER_METHOD(ProcessUInt, { L"value" })
			END_INTERFACE_MEMBER(::RpcPrimitiveTest::IService)

			BEGIN_STRUCT_MEMBER(::RpcPrimitiveTest::Point)
				STRUCT_MEMBER(x)
				STRUCT_MEMBER(y)
			END_STRUCT_MEMBER(::RpcPrimitiveTest::Point)

			BEGIN_ENUM_ITEM(::RpcPrimitiveTest::Season)
				ENUM_CLASS_ITEM(Autumn)
				ENUM_CLASS_ITEM(Spring)
				ENUM_CLASS_ITEM(Summer)
				ENUM_CLASS_ITEM(Winter)
			END_ENUM_ITEM(::RpcPrimitiveTest::Season)

			BEGIN_INTERFACE_MEMBER(::rpcops_IOps_Rpc_PrimitiveTypes)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessBool, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessDouble, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessEnum, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessFloat, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessInt, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessString, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessStruct, { L"ref" _ L"arg_value" })
				CLASS_MEMBER_METHOD(InvokeMethod_RpcPrimitiveTest__IService_ProcessUInt, { L"ref" _ L"arg_value" })
			END_INTERFACE_MEMBER(::rpcops_IOps_Rpc_PrimitiveTypes)

#undef _
			class Rpc_PrimitiveTypesTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::RpcPrimitiveTest::IRpcWrapper_IService)
					ADD_TYPE_INFO(::RpcPrimitiveTest::IService)
					ADD_TYPE_INFO(::RpcPrimitiveTest::Point)
					ADD_TYPE_INFO(::RpcPrimitiveTest::Season)
					ADD_TYPE_INFO(::rpcops_IOps_Rpc_PrimitiveTypes)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadRpc_PrimitiveTypesTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new Rpc_PrimitiveTypesTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
