/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/RequestService.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "RequestServiceReflection.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			IMPL_CPP_TYPE_INFO(RpcTest::IRpcWrapper_IService)
			IMPL_CPP_TYPE_INFO(RpcTest::IService)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
#define _ ,
			BEGIN_INTERFACE_MEMBER(::RpcTest::IRpcWrapper_IService)
				CLASS_MEMBER_BASE(::RpcTest::IService)
				CLASS_MEMBER_BASE(::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_MEMBER(::RpcTest::IRpcWrapper_IService)

			BEGIN_INTERFACE_MEMBER(::RpcTest::IService)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_rpc_Interface)
				ATTRIBUTE_TYPE(::vl::__vwsn::att_rpc_Ctor)
				CLASS_MEMBER_BASE(::vl::reflection::IDescriptable)
				CLASS_MEMBER_METHOD(GetText, NO_PARAMETER)
			END_INTERFACE_MEMBER(::RpcTest::IService)

#undef _
			class RequestServiceTypeLoader : public Object, public ITypeLoader
			{
			public:
				void Load(ITypeManager* manager)
				{
					ADD_TYPE_INFO(::RpcTest::IRpcWrapper_IService)
					ADD_TYPE_INFO(::RpcTest::IService)
				}

				void Unload(ITypeManager* manager)
				{
				}
			};
#endif
#endif

			bool LoadRequestServiceTypes()
			{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
				if (auto manager = GetGlobalTypeManager())
				{
					return manager->AddTypeLoader(Ptr(new RequestServiceTypeLoader));
				}
#endif
				return false;
			}
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
