/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/Inheritance_MethodException.txt; ../Resources/Rpc/Inheritance_MethodException_Test.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#include "RpcInheritance_MethodException.h"
/* CodePack:BeginIgnore() */
#ifndef VCZH_DEBUG_NO_REFLECTION
/* CodePack:ConditionOff(VCZH_DEBUG_NO_REFLECTION, RpcInheritance_MethodExceptionReflection.h) */
#include "RpcInheritance_MethodExceptionReflection.h"
#endif
/* CodePack:EndIgnore() */

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

#define GLOBAL_SYMBOL ::vl_workflow_global::Rpc_Inheritance_MethodException::
#define GLOBAL_NAME ::vl_workflow_global::Rpc_Inheritance_MethodException::Instance().
#define GLOBAL_OBJ &::vl_workflow_global::Rpc_Inheritance_MethodException::Instance()

/***********************************************************************
Global Variables
***********************************************************************/

BEGIN_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_Inheritance_MethodException)
	vl_workflow_global::Rpc_Inheritance_MethodException instance;
	INITIALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Unmanaged(L"");
		instance.rpctype_RpcInheritanceMethodException__IDerived = static_cast<::vl::vint>(0);
		instance.rpctype_RpcInheritanceMethodException__IOne = static_cast<::vl::vint>(1);
		instance.rpcmethod_RpcInheritanceMethodException__IOne_SetOneValue = static_cast<::vl::vint>(2);
		instance.rpctype_RpcInheritanceMethodException__IService = static_cast<::vl::vint>(3);
		instance.rpcmethod_RpcInheritanceMethodException__IService_CreateDerived = static_cast<::vl::vint>(4);
		instance.rpctype_RpcInheritanceMethodException__ITwo = static_cast<::vl::vint>(5);
		instance.rpcmethod_RpcInheritanceMethodException__ITwo_SetTwoValue = static_cast<::vl::vint>(6);
		instance.rpctype_RpcInheritanceMethodException__IValue = static_cast<::vl::vint>(7);
	FINALIZE_GLOBAL_STORAGE_CLASS

		instance.s = ::vl::WString::Empty;
END_GLOBAL_STORAGE_CLASS(vl_workflow_global_Rpc_Inheritance_MethodException)

namespace vl_workflow_global
{
/***********************************************************************
Global Functions
***********************************************************************/

	void Rpc_Inheritance_MethodException::serviceMain(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		auto serviceObj = ::vl::Ptr<::RpcInheritanceMethodException::IService>(new ::vl_workflow_global::__vwsnc1_Rpc_Inheritance_MethodException_serviceMain__RpcInheritanceMethodException_IService());
		::vl::__vwsn::This(lc)->RegisterLocalService(::vl::__vwsn::Unbox<::vl::vint>(::vl::__vwsn::This(GLOBAL_NAME rpc_GetIds().Obj())->Get(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IService")))), ::vl::Ptr<::vl::reflection::IDescriptable>(serviceObj));
	}

	::vl::WString Rpc_Inheritance_MethodException::clientMain(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		auto service = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IService>(::vl::__vwsn::This(lc)->RequestService(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IService")).Obj()));
		auto derived = ::vl::__vwsn::This(service.Obj())->CreateDerived();
		(GLOBAL_NAME s = ((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[]")));
		try
		{
			{
				::vl::__vwsn::This(derived.Obj())->SetOneValue();
			}
		}
		catch(const ::vl::Exception& __vwsne_0)
		{
			auto ex = ::vl::reflection::description::IValueException::Create(__vwsne_0.Message());
			{
				(GLOBAL_NAME s = ((((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::This(ex.Obj())->GetMessage()) + ::vl::WString::Unmanaged(L"]")));
			}
		}
		(GLOBAL_NAME s = ((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[]")));
		try
		{
			{
				::vl::__vwsn::This(derived.Obj())->SetTwoValue();
			}
		}
		catch(const ::vl::Exception& __vwsne_1)
		{
			auto ex = ::vl::reflection::description::IValueException::Create(__vwsne_1.Message());
			{
				(GLOBAL_NAME s = ((((::vl::WString::Unmanaged(L"") + GLOBAL_NAME s) + ::vl::WString::Unmanaged(L"[")) + ::vl::__vwsn::This(ex.Obj())->GetMessage()) + ::vl::WString::Unmanaged(L"]")));
			}
		}
		return GLOBAL_NAME s;
	}

	::vl::Ptr<::vl::reflection::description::IValueDictionary> Rpc_Inheritance_MethodException::rpc_GetIds()
	{
		auto result = ::vl::reflection::description::IValueDictionary::Create();
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IDerived")), ::vl::__vwsn::Box(static_cast<::vl::vint>(0)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IOne")), ::vl::__vwsn::Box(static_cast<::vl::vint>(1)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IOne.SetOneValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(2)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IService")), ::vl::__vwsn::Box(static_cast<::vl::vint>(3)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IService.CreateDerived")), ::vl::__vwsn::Box(static_cast<::vl::vint>(4)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::ITwo")), ::vl::__vwsn::Box(static_cast<::vl::vint>(5)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::ITwo.SetTwoValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(6)));
		::vl::__vwsn::This(result.Obj())->Set(::vl::__vwsn::Box(::vl::WString::Unmanaged(L"RpcInheritanceMethodException::IValue")), ::vl::__vwsn::Box(static_cast<::vl::vint>(7)));
		return result;
	}

	bool Rpc_Inheritance_MethodException::rpcwrapper_IsInterfaceTypeId(::vl::vint typeId)
	{
		if (((typeId >= static_cast<::vl::vint>(-7)) && (typeId <= static_cast<::vl::vint>(-1))))
			return true;
		{
			auto __vwsn_switch_0 = typeId;
			if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IValue))
				return true;
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IOne))
				return true;
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__ITwo))
				return true;
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IDerived))
				return true;
			else if ((__vwsn_switch_0 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IService))
				return true;
			else
				return false;
		}
	}

	bool Rpc_Inheritance_MethodException::rpcwrapper_IsCtorInterfaceTypeId(::vl::vint typeId)
	{
		{
			auto __vwsn_switch_1 = typeId;
			if ((__vwsn_switch_1 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IService))
				return true;
			else
				return false;
		}
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> Rpc_Inheritance_MethodException::rpcops_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectOps>(new ::vl_workflow_global::__vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(lc));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> Rpc_Inheritance_MethodException::rpcops_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps>(new ::vl_workflow_global::__vwsnc4_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(lc));
	}

	::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> Rpc_Inheritance_MethodException::rpcops_IOps_Create(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>(new ::vl_workflow_global::__vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException(lc));
	}

	::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IValue> Rpc_Inheritance_MethodException::rpcwrapper_RpcInheritanceMethodException__IValue(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		auto proxy = ::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IValue>(new ::vl_workflow_global::__vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue(lc, ops, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IOne> Rpc_Inheritance_MethodException::rpcwrapper_RpcInheritanceMethodException__IOne(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		auto proxy = ::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IOne>(new ::vl_workflow_global::__vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne(lc, ops, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_ITwo> Rpc_Inheritance_MethodException::rpcwrapper_RpcInheritanceMethodException__ITwo(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		auto proxy = ::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_ITwo>(new ::vl_workflow_global::__vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo(lc, ops, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IDerived> Rpc_Inheritance_MethodException::rpcwrapper_RpcInheritanceMethodException__IDerived(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		auto proxy = ::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IDerived>(new ::vl_workflow_global::__vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived(lc, ops, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IService> Rpc_Inheritance_MethodException::rpcwrapper_RpcInheritanceMethodException__IService(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		auto proxy = ::vl::Ptr<::RpcInheritanceMethodException::IRpcWrapper_IService>(new ::vl_workflow_global::__vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService(lc, ops, proxyRef));
		::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(lc)->GetDispatcher())->SendToClient_ObjectOps(proxyRef.clientId))->ObjectHold(proxyRef, ::vl::__vwsn::This(lc)->GetClientId(), true);
		return proxy;
	}

	::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> Rpc_Inheritance_MethodException::rpcwrapper_Create(::vl::rpc_controller::RpcObjectReference ref, ::vl::rpc_controller::IRpcLifecycle* lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> ops)
	{
		{
			auto __vwsn_switch_3 = ref.typeId;
			if ((__vwsn_switch_3 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IValue))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcInheritanceMethodException__IValue(lc, ref, ops));
			}
			else if ((__vwsn_switch_3 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IOne))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcInheritanceMethodException__IOne(lc, ref, ops));
			}
			else if ((__vwsn_switch_3 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__ITwo))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcInheritanceMethodException__ITwo(lc, ref, ops));
			}
			else if ((__vwsn_switch_3 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IDerived))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcInheritanceMethodException__IDerived(lc, ref, ops));
			}
			else if ((__vwsn_switch_3 == GLOBAL_NAME rpctype_RpcInheritanceMethodException__IService))
			{
				return ::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase>(GLOBAL_NAME rpcwrapper_RpcInheritanceMethodException__IService(lc, ref, ops));
			}
			else
				throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC type id for wrapper creation."));
		}
	}

	::vl::Ptr<::vl::glr::json::JsonNode> Rpc_Inheritance_MethodException::rpcjson_Serialize(const ::vl::reflection::description::Value& value)
	{
		return ::vl::rpc_controller::JsonSerializePredefinedTypes(value, ::vl::Func<::vl::Ptr<::vl::glr::json::JsonNode>(const ::vl::reflection::description::Value&)>(GLOBAL_OBJ, &GLOBAL_SYMBOL rpcjson_Serialize));
	}

	::vl::reflection::description::Value Rpc_Inheritance_MethodException::rpcjson_Deserialize(::vl::Ptr<::vl::glr::json::JsonNode> node)
	{
		auto object = ::vl::__vwsn::SharedPtrCast<::vl::glr::json::JsonObject>(node.Obj());
		if (static_cast<bool>(object))
		{
			auto jsonFieldValue0 = ::vl::Ptr<::vl::glr::json::JsonNode>();
			{
				auto __vwsn_for_enumerable_jsonField1 = ::vl::Ptr<::vl::reflection::description::IValueEnumerable>(::vl::__vwsn::UnboxCollection<::vl::reflection::description::IValueList>(::vl::__vwsn::This(object.Obj())->fields));
				auto __vwsn_for_enumerator_jsonField1 = ::vl::__vwsn::This(__vwsn_for_enumerable_jsonField1.Obj())->CreateEnumerator();
				while (::vl::__vwsn::This(__vwsn_for_enumerator_jsonField1.Obj())->Next())
				{
					auto jsonField1 = ::vl::__vwsn::Unbox<::vl::Ptr<::vl::glr::json::JsonObjectField>>(::vl::__vwsn::This(__vwsn_for_enumerator_jsonField1.Obj())->GetCurrent());
					{
						if ((::vl::__vwsn::This(jsonField1.Obj())->name.value == ::vl::WString::Unmanaged(L"$")))
							(jsonFieldValue0 = ::vl::__vwsn::This(jsonField1.Obj())->value);
					}
				}
			}
			if (static_cast<bool>(jsonFieldValue0))
			{
				auto keyword = ::vl::__vwsn::This(::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::vl::glr::json::JsonString>(jsonFieldValue0.Obj())).Obj())->content.value;
				{
					auto __vwsn_switch_4 = keyword;
				}
			}
		}
		return ::vl::rpc_controller::JsonDeserializePredefinedTypes(::vl::__vwsn::Box(node), ::vl::Func<::vl::reflection::description::Value(::vl::Ptr<::vl::glr::json::JsonNode>)>(GLOBAL_OBJ, &GLOBAL_SYMBOL rpcjson_Deserialize));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcSerializer> Rpc_Inheritance_MethodException::rpcops_IRpcSerializer()
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcSerializer>(new ::vl_workflow_global::__vwsnc11_Rpc_Inheritance_MethodException_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer());
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> Rpc_Inheritance_MethodException::rpcops_IRpcObjectOpsJson(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectOps>(new ::vl_workflow_global::__vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps(lc));
	}

	::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> Rpc_Inheritance_MethodException::rpcops_IRpcObjectEventOpsJson(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps>(new ::vl_workflow_global::__vwsnc13_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps(lc));
	}

	::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> Rpc_Inheritance_MethodException::rpcops_IOps_CreateJson(::vl::rpc_controller::IRpcLifecycle* lc)
	{
		return ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>(new ::vl_workflow_global::__vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException(lc));
	}

	Rpc_Inheritance_MethodException& Rpc_Inheritance_MethodException::Instance()
	{
		return Getvl_workflow_global_Rpc_Inheritance_MethodException().instance;
	}

/***********************************************************************
Closures
***********************************************************************/

	//-------------------------------------------------------------------

	__vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService::__vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->_ops = __vwsnctor_ops;
	}

	void __vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
		(_ops = ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>());
	}

	__vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService::~__vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	::vl::Ptr<::RpcInheritanceMethodException::IDerived> __vwsnc10_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IService__RpcInheritanceMethodException_IRpcWrapper_IService::CreateDerived()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		return ::vl::__vwsn::This(_ops.Obj())->InvokeMethod_RpcInheritanceMethodException__IService_CreateDerived(_ref);
	}

	//-------------------------------------------------------------------

	__vwsnc11_Rpc_Inheritance_MethodException_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer::__vwsnc11_Rpc_Inheritance_MethodException_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer()
	{
	}

	::vl::reflection::description::Value __vwsnc11_Rpc_Inheritance_MethodException_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer::Serialize(const ::vl::reflection::description::Value& value)
	{
		auto result = GLOBAL_NAME rpcjson_Serialize(value);
		return ::vl::__vwsn::Box(result);
	}

	::vl::reflection::description::Value __vwsnc11_Rpc_Inheritance_MethodException_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer::Deserialize(const ::vl::reflection::description::Value& value)
	{
		return GLOBAL_NAME rpcjson_Deserialize(::vl::__vwsn::Unbox<::vl::Ptr<::vl::glr::json::JsonNode>>(value));
	}

	//-------------------------------------------------------------------

	__vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps::__vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
		this->_slot = static_cast<::vl::vint>(0);
		this->_byvalReturnValues = ::vl::reflection::description::IValueDictionary::Create();
	}

	::vl::reflection::description::Value __vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps::InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		auto unknownId = false;
		try
		{
			{
				auto __vwsn_switch_5 = methodId;
				if ((__vwsn_switch_5 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IOne_SetOneValue))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IOne>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					::vl::__vwsn::This(target.Obj())->SetOneValue();
					auto jsonLiteral0 = ::vl::Ptr<::vl::glr::json::JsonLiteral>(new ::vl::glr::json::JsonLiteral());
					(::vl::__vwsn::This(jsonLiteral0.Obj())->value = ::vl::glr::json::JsonLiteralValue::Null);
					return ::vl::__vwsn::Box(jsonLiteral0);
				}
				else if ((__vwsn_switch_5 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__ITwo_SetTwoValue))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::ITwo>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					::vl::__vwsn::This(target.Obj())->SetTwoValue();
					auto jsonLiteral0 = ::vl::Ptr<::vl::glr::json::JsonLiteral>(new ::vl::glr::json::JsonLiteral());
					(::vl::__vwsn::This(jsonLiteral0.Obj())->value = ::vl::glr::json::JsonLiteralValue::Null);
					return ::vl::__vwsn::Box(jsonLiteral0);
				}
				else if ((__vwsn_switch_5 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IService_CreateDerived))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					auto jsonValue0 = ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->CreateDerived()), _lc);
					auto jsonNode1 = GLOBAL_NAME rpcjson_Serialize(jsonValue0);
					return ::vl::__vwsn::Box(jsonNode1);
				}
				else
					(unknownId = true);
			}
		}
		catch(const ::vl::Exception& __vwsne_0)
		{
			auto ex = ::vl::reflection::description::IValueException::Create(__vwsne_0.Message());
			{
				return ::vl::__vwsn::Box(GLOBAL_NAME rpcjson_Serialize(::vl::__vwsn::Box([&](){ ::vl::rpc_controller::RpcException __vwsn_temp__; __vwsn_temp__.message = ::vl::__vwsn::This(ex.Obj())->GetMessage(); return __vwsn_temp__; }())));
			}
		}
		if (unknownId)
		{
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC method id."));
		}
		return ::vl::__vwsn::Box(GLOBAL_NAME rpcjson_Serialize(::vl::reflection::description::Value()));
	}

	void __vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps::EndInvokeMethod(::vl::vint slot)
	{
		::vl::__vwsn::This(_byvalReturnValues.Obj())->Remove(::vl::__vwsn::Box(slot));
	}

	void __vwsnc12_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps::ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold)
	{
		if (hold)
		{
			::vl::__vwsn::This(_lc)->LocalObjectHold(ref, remoteClientId);
		}
		else
		{
			::vl::__vwsn::This(_lc)->LocalObjectUnhold(ref, remoteClientId);
		}
	}

	//-------------------------------------------------------------------

	__vwsnc13_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps::__vwsnc13_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	::vl::reflection::description::Value __vwsnc13_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps::InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC event id."));
	}

	//-------------------------------------------------------------------

	__vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException::__vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	void __vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__IOne_SetOneValue(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IOne_SetOneValue, arguments);
		auto jsonResult = ::vl::__vwsn::Unbox<::vl::Ptr<::vl::glr::json::JsonNode>>(invokeResult);
		auto methodResult = GLOBAL_NAME rpcjson_Deserialize(jsonResult);
		::vl::rpc_controller::ReadMethodException(methodResult);
	}

	void __vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__ITwo_SetTwoValue(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__ITwo_SetTwoValue, arguments);
		auto jsonResult = ::vl::__vwsn::Unbox<::vl::Ptr<::vl::glr::json::JsonNode>>(invokeResult);
		auto methodResult = GLOBAL_NAME rpcjson_Deserialize(jsonResult);
		::vl::rpc_controller::ReadMethodException(methodResult);
	}

	::vl::Ptr<::RpcInheritanceMethodException::IDerived> __vwsnc14_Rpc_Inheritance_MethodException_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__IService_CreateDerived(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IService_CreateDerived, arguments);
		auto jsonResult = ::vl::__vwsn::Unbox<::vl::Ptr<::vl::glr::json::JsonNode>>(invokeResult);
		auto methodResult = GLOBAL_NAME rpcjson_Deserialize(jsonResult);
		::vl::rpc_controller::ReadMethodException(methodResult);
		auto jsonValue0 = GLOBAL_NAME rpcjson_Deserialize(jsonResult);
		return ::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IDerived>(::vl::rpc_controller::RpcUnboxByval(jsonValue0, _lc).Obj());
	}

	//-------------------------------------------------------------------

	__vwsnc1_Rpc_Inheritance_MethodException_serviceMain__RpcInheritanceMethodException_IService::__vwsnc1_Rpc_Inheritance_MethodException_serviceMain__RpcInheritanceMethodException_IService()
	{
	}

	::vl::Ptr<::RpcInheritanceMethodException::IDerived> __vwsnc1_Rpc_Inheritance_MethodException_serviceMain__RpcInheritanceMethodException_IService::CreateDerived()
	{
		return ::vl::Ptr<::RpcInheritanceMethodException::IDerived>(new ::vl_workflow_global::__vwsnc2_Rpc_Inheritance_MethodException_serviceMain_CreateDerived__RpcInheritanceMethodException_IDerived(this));
	}

	//-------------------------------------------------------------------

	__vwsnc2_Rpc_Inheritance_MethodException_serviceMain_CreateDerived__RpcInheritanceMethodException_IDerived::__vwsnc2_Rpc_Inheritance_MethodException_serviceMain_CreateDerived__RpcInheritanceMethodException_IDerived(::RpcInheritanceMethodException::IService* __vwsnctorthis_0)
		:__vwsnthis_0(::vl::__vwsn::This(__vwsnctorthis_0))
	{
	}

	void __vwsnc2_Rpc_Inheritance_MethodException_serviceMain_CreateDerived__RpcInheritanceMethodException_IDerived::SetOneValue()
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"DoNotSetOneValue"));
	}

	void __vwsnc2_Rpc_Inheritance_MethodException_serviceMain_CreateDerived__RpcInheritanceMethodException_IDerived::SetTwoValue()
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"DoNotSetTwoValue"));
	}

	//-------------------------------------------------------------------

	__vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::__vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
		this->_slot = static_cast<::vl::vint>(0);
		this->_byvalReturnValues = ::vl::reflection::description::IValueDictionary::Create();
	}

	::vl::reflection::description::Value __vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		auto unknownId = false;
		try
		{
			{
				auto __vwsn_switch_2 = methodId;
				if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IOne_SetOneValue))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IOne>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					::vl::__vwsn::This(target.Obj())->SetOneValue();
					return ::vl::reflection::description::Value();
				}
				else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__ITwo_SetTwoValue))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::ITwo>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					::vl::__vwsn::This(target.Obj())->SetTwoValue();
					return ::vl::reflection::description::Value();
				}
				else if ((__vwsn_switch_2 == GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IService_CreateDerived))
				{
					auto target = ::vl::__vwsn::Ensure(::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IService>(::vl::__vwsn::This(_lc)->RefToPtr(ref).Obj()));
					return ::vl::rpc_controller::RpcBoxByval(::vl::__vwsn::Box(::vl::__vwsn::This(target.Obj())->CreateDerived()), _lc);
				}
				else
					(unknownId = true);
			}
		}
		catch(const ::vl::Exception& __vwsne_0)
		{
			auto ex = ::vl::reflection::description::IValueException::Create(__vwsne_0.Message());
			{
				return ::vl::__vwsn::Box([&](){ ::vl::rpc_controller::RpcException __vwsn_temp__; __vwsn_temp__.message = ::vl::__vwsn::This(ex.Obj())->GetMessage(); return __vwsn_temp__; }());
			}
		}
		if (unknownId)
		{
			throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC method id."));
		}
		return ::vl::reflection::description::Value();
	}

	void __vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::EndInvokeMethod(::vl::vint slot)
	{
		::vl::__vwsn::This(_byvalReturnValues.Obj())->Remove(::vl::__vwsn::Box(slot));
	}

	void __vwsnc3_Rpc_Inheritance_MethodException_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps::ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold)
	{
		if (hold)
		{
			::vl::__vwsn::This(_lc)->LocalObjectHold(ref, remoteClientId);
		}
		else
		{
			::vl::__vwsn::This(_lc)->LocalObjectUnhold(ref, remoteClientId);
		}
	}

	//-------------------------------------------------------------------

	__vwsnc4_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::__vwsnc4_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	::vl::reflection::description::Value __vwsnc4_Rpc_Inheritance_MethodException_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps::InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments)
	{
		throw ::vl::Exception(::vl::WString::Unmanaged(L"Unknown RPC event id."));
	}

	//-------------------------------------------------------------------

	__vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException::__vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc)
	{
		this->_lc = __vwsnctor_lc;
	}

	void __vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__IOne_SetOneValue(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IOne_SetOneValue, arguments);
		::vl::rpc_controller::ReadMethodException(invokeResult);
	}

	void __vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__ITwo_SetTwoValue(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__ITwo_SetTwoValue, arguments);
		::vl::rpc_controller::ReadMethodException(invokeResult);
	}

	::vl::Ptr<::RpcInheritanceMethodException::IDerived> __vwsnc5_Rpc_Inheritance_MethodException_rpcops_IOps_Create__rpcops_IOps_Rpc_Inheritance_MethodException::InvokeMethod_RpcInheritanceMethodException__IService_CreateDerived(::vl::rpc_controller::RpcObjectReference ref)
	{
		auto arguments = ::vl::reflection::description::IValueArray::Create();
		::vl::__vwsn::This(arguments.Obj())->Resize(static_cast<::vl::vint>(0));
		auto invokeResult = ::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(ref.clientId))->InvokeMethod(ref, GLOBAL_NAME rpcmethod_RpcInheritanceMethodException__IService_CreateDerived, arguments);
		::vl::rpc_controller::ReadMethodException(invokeResult);
		return ::vl::__vwsn::SharedPtrCast<::RpcInheritanceMethodException::IDerived>(::vl::rpc_controller::RpcUnboxByval(invokeResult, _lc).Obj());
	}

	//-------------------------------------------------------------------

	__vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue::__vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->_ops = __vwsnctor_ops;
	}

	void __vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
		(_ops = ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>());
	}

	__vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue::~__vwsnc6_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IValue__RpcInheritanceMethodException_IRpcWrapper_IValue()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	//-------------------------------------------------------------------

	__vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne::__vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->_ops = __vwsnctor_ops;
	}

	void __vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
		(_ops = ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>());
	}

	__vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne::~__vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	void __vwsnc7_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IOne__RpcInheritanceMethodException_IRpcWrapper_IOne::SetOneValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		::vl::__vwsn::This(_ops.Obj())->InvokeMethod_RpcInheritanceMethodException__IOne_SetOneValue(_ref);
	}

	//-------------------------------------------------------------------

	__vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo::__vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->_ops = __vwsnctor_ops;
	}

	void __vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
		(_ops = ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>());
	}

	__vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo::~__vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	void __vwsnc8_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__ITwo__RpcInheritanceMethodException_IRpcWrapper_ITwo::SetTwoValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		::vl::__vwsn::This(_ops.Obj())->InvokeMethod_RpcInheritanceMethodException__ITwo_SetTwoValue(_ref);
	}

	//-------------------------------------------------------------------

	__vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived::__vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef)
	{
		this->_lc = __vwsnctor_lc;
		this->_ref = __vwsnctor_proxyRef;
		this->_ops = __vwsnctor_ops;
	}

	void __vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived::DisconnectFromLifecycle()
	{
		(_lc = static_cast<::vl::rpc_controller::IRpcLifecycle*>(nullptr));
		(_ops = ::vl::Ptr<::rpcops_IOps_Rpc_Inheritance_MethodException>());
	}

	__vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived::~__vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived()
	{
		if ((_lc != nullptr))
		{
			::vl::__vwsn::This(::vl::__vwsn::This(::vl::__vwsn::This(_lc)->GetDispatcher())->SendToClient_ObjectOps(_ref.clientId))->ObjectHold(_ref, ::vl::__vwsn::This(_lc)->GetClientId(), false);
		}
	}

	void __vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived::SetOneValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		::vl::__vwsn::This(_ops.Obj())->InvokeMethod_RpcInheritanceMethodException__IOne_SetOneValue(_ref);
	}

	void __vwsnc9_Rpc_Inheritance_MethodException_rpcwrapper_RpcInheritanceMethodException__IDerived__RpcInheritanceMethodException_IRpcWrapper_IDerived::SetTwoValue()
	{
		if ((_lc == nullptr))
			throw ::vl::Exception(::vl::WString::Unmanaged(L"RPC wrapper has been disconnected from lifecycle."));
		::vl::__vwsn::This(_ops.Obj())->InvokeMethod_RpcInheritanceMethodException__ITwo_SetTwoValue(_ref);
	}

}

/***********************************************************************
Class (::RpcInheritanceMethodException::IService)
***********************************************************************/

namespace RpcInheritanceMethodException
{
/***********************************************************************
Class (::RpcInheritanceMethodException::IRpcWrapper_IService)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IValue)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IOne)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IRpcWrapper_IOne)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IRpcWrapper_IValue)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::ITwo)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IDerived)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IRpcWrapper_IDerived)
***********************************************************************/

/***********************************************************************
Class (::RpcInheritanceMethodException::IRpcWrapper_ITwo)
***********************************************************************/

/***********************************************************************
Class (::rpcops_IOps_Rpc_Inheritance_MethodException)
***********************************************************************/

}
#undef GLOBAL_SYMBOL
#undef GLOBAL_NAME
#undef GLOBAL_OBJ

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
