/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/PropDefaultInterfaceList.txt; ../Resources/Rpc/PropDefaultInterfaceList_Test.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_RPCPROPDEFAULTINTERFACELISTREFLECTION
#define VCZH_WORKFLOW_COMPILER_GENERATED_RPCPROPDEFAULTINTERFACELISTREFLECTION

#include "RpcPropDefaultInterfaceList.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

/***********************************************************************
Reflection
***********************************************************************/

namespace vl
{
	namespace reflection
	{
		namespace description
		{
#ifndef VCZH_DEBUG_NO_REFLECTION
			DECL_TYPE_INFO(::RpcPropDefaultInterfaceList::IRpcWrapper_IService)
			DECL_TYPE_INFO(::RpcPropDefaultInterfaceList::IRpcWrapper_IValue)
			DECL_TYPE_INFO(::RpcPropDefaultInterfaceList::IService)
			DECL_TYPE_INFO(::RpcPropDefaultInterfaceList::IValue)
			DECL_TYPE_INFO(::rpcops_IOps_Rpc_PropDefaultInterfaceList)

#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcPropDefaultInterfaceList::IService)
				::vl::Ptr<::vl::reflection::description::IValueList> GetValue() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetValue);
				}
				void SetValue(::vl::Ptr<::vl::reflection::description::IValueList> value) override
				{
					INVOKE_INTERFACE_PROXY(SetValue, value);
				}
				void Signal() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(Signal);
				}
			END_INTERFACE_PROXY(::RpcPropDefaultInterfaceList::IService)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::RpcPropDefaultInterfaceList::IValue)
				::vl::WString GetValue() override
				{
					INVOKEGET_INTERFACE_PROXY_NOPARAMS(GetValue);
				}
			END_INTERFACE_PROXY(::RpcPropDefaultInterfaceList::IValue)

			BEGIN_INTERFACE_PROXY_NOPARENT_SHAREDPTR(::rpcops_IOps_Rpc_PropDefaultInterfaceList)
				void InvokeEvent_RpcPropDefaultInterfaceList__IService_ValueChanged(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeEvent_RpcPropDefaultInterfaceList__IService_ValueChanged, ref);
				}
				::vl::Ptr<::vl::reflection::description::IValueList> InvokeMethod_RpcPropDefaultInterfaceList__IService_GetValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcPropDefaultInterfaceList__IService_GetValue, ref);
				}
				void InvokeMethod_RpcPropDefaultInterfaceList__IService_SetValue(::vl::rpc_controller::RpcObjectReference ref, ::vl::Ptr<::vl::reflection::description::IValueList> arg_value) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcPropDefaultInterfaceList__IService_SetValue, ref, arg_value);
				}
				void InvokeMethod_RpcPropDefaultInterfaceList__IService_Signal(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKE_INTERFACE_PROXY(InvokeMethod_RpcPropDefaultInterfaceList__IService_Signal, ref);
				}
				::vl::WString InvokeMethod_RpcPropDefaultInterfaceList__IValue_GetValue(::vl::rpc_controller::RpcObjectReference ref) override
				{
					INVOKEGET_INTERFACE_PROXY(InvokeMethod_RpcPropDefaultInterfaceList__IValue_GetValue, ref);
				}
			END_INTERFACE_PROXY(::rpcops_IOps_Rpc_PropDefaultInterfaceList)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcPropDefaultInterfaceList::IRpcWrapper_IService, ::RpcPropDefaultInterfaceList::IService, ::vl::rpc_controller::IRpcWrapperBase)
				void _rpcInvalidate_Value() override
				{
					INVOKE_INTERFACE_PROXY_NOPARAMS(_rpcInvalidate_Value);
				}
			END_INTERFACE_PROXY(::RpcPropDefaultInterfaceList::IRpcWrapper_IService)

			BEGIN_INTERFACE_PROXY_SHAREDPTR(::RpcPropDefaultInterfaceList::IRpcWrapper_IValue, ::RpcPropDefaultInterfaceList::IValue, ::vl::rpc_controller::IRpcWrapperBase)
			END_INTERFACE_PROXY(::RpcPropDefaultInterfaceList::IRpcWrapper_IValue)
#endif
#endif

			extern bool LoadRpc_PropDefaultInterfaceListTypes();
		}
	}
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
