/***********************************************************************
!!!!!! DO NOT MODIFY !!!!!!

Source: ../Resources/Rpc/PropDynamic.txt; ../Resources/Rpc/PropDynamic_Test.txt

This file is generated by Workflow compiler
https://github.com/vczh-libraries
***********************************************************************/

#ifndef VCZH_WORKFLOW_COMPILER_GENERATED_RPCPROPDYNAMIC
#define VCZH_WORKFLOW_COMPILER_GENERATED_RPCPROPDYNAMIC

#include "../Source/CppTypes.h"
#include "../../Import/VlppGlrParser.h"

#if defined( _MSC_VER)
#pragma warning(push)
#pragma warning(disable:4250)
#elif defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wparentheses-equality"
#elif defined(__GNUC__)
#pragma GCC diagnostic push
#endif

namespace vl_workflow_global
{
	struct __vwsnf1_Rpc_PropDynamic_rpclistener_RpcPropDynamic__IService_;
	class __vwsnc1_Rpc_PropDynamic_serviceMain__RpcPropDynamic_IService;
	class __vwsnc2_Rpc_PropDynamic_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps;
	class __vwsnc3_Rpc_PropDynamic_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps;
	class __vwsnc4_Rpc_PropDynamic_rpcops_IOps_Create__rpcops_IOps_Rpc_PropDynamic;
	class __vwsnc5_Rpc_PropDynamic_rpcwrapper_RpcPropDynamic__IService__RpcPropDynamic_IRpcWrapper_IService;
	class __vwsnc6_Rpc_PropDynamic_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer;
	class __vwsnc7_Rpc_PropDynamic_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps;
	class __vwsnc8_Rpc_PropDynamic_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps;
	class __vwsnc9_Rpc_PropDynamic_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_PropDynamic;
}

namespace RpcPropDynamic
{
	class IService;
	class IRpcWrapper_IService;
}
class rpcops_IOps_Rpc_PropDynamic;

namespace RpcPropDynamic
{
	class IService : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<IService>
	{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IService>;
#endif
	public:
		virtual ::vl::WString GetValue() = 0;
		virtual void SetValue(const ::vl::WString& value) = 0;
		virtual void Signal() = 0;
		::vl::Event<void()> ValueChanged;
	};

	class IRpcWrapper_IService : public virtual ::RpcPropDynamic::IService, public virtual ::vl::rpc_controller::IRpcWrapperBase, public ::vl::reflection::Description<IRpcWrapper_IService>
	{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
		friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<IRpcWrapper_IService>;
#endif
	};

}
class rpcops_IOps_Rpc_PropDynamic : public virtual ::vl::reflection::IDescriptable, public ::vl::reflection::Description<rpcops_IOps_Rpc_PropDynamic>
{
#ifdef VCZH_DESCRIPTABLEOBJECT_WITH_METADATA
	friend struct ::vl::reflection::description::CustomTypeDescriptorSelector<rpcops_IOps_Rpc_PropDynamic>;
#endif
public:
	virtual ::vl::WString InvokeMethod_RpcPropDynamic__IService_GetValue(::vl::rpc_controller::RpcObjectReference ref) = 0;
	virtual void InvokeMethod_RpcPropDynamic__IService_SetValue(::vl::rpc_controller::RpcObjectReference ref, const ::vl::WString& arg_value) = 0;
	virtual void InvokeMethod_RpcPropDynamic__IService_Signal(::vl::rpc_controller::RpcObjectReference ref) = 0;
	virtual void InvokeEvent_RpcPropDynamic__IService_ValueChanged(::vl::rpc_controller::RpcObjectReference ref) = 0;
};

/***********************************************************************
Global Variables and Functions
***********************************************************************/

namespace vl_workflow_global
{
	class Rpc_PropDynamic
	{
	public:

		::vl::WString s;
		::vl::vint rpctype_RpcPropDynamic__IService = 0;
		::vl::vint rpcmethod_RpcPropDynamic__IService_GetValue = 0;
		::vl::vint rpcmethod_RpcPropDynamic__IService_SetValue = 0;
		::vl::vint rpcmethod_RpcPropDynamic__IService_Signal = 0;
		::vl::vint rpcevent_RpcPropDynamic__IService_ValueChanged = 0;

		void ClientValueChanged();
		void serviceMain(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::WString clientMain(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::Ptr<::vl::reflection::description::IValueDictionary> rpc_GetIds();
		bool rpcwrapper_IsInterfaceTypeId(::vl::vint typeId);
		bool rpcwrapper_IsCtorInterfaceTypeId(::vl::vint typeId);
		::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> rpcops_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> rpcops_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> rpcops_IOps_Create(::vl::rpc_controller::IRpcLifecycle* lc);
		void rpclistener_RpcPropDynamic__IService(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference ref, ::RpcPropDynamic::IService* target, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> ops);
		void rpclistener_Attach(::vl::vint typeId, ::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference ref, ::vl::reflection::IDescriptable* obj, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> ops);
		::vl::Ptr<::RpcPropDynamic::IRpcWrapper_IService> rpcwrapper_RpcPropDynamic__IService(::vl::rpc_controller::IRpcLifecycle* lc, ::vl::rpc_controller::RpcObjectReference proxyRef, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> ops);
		::vl::Ptr<::vl::rpc_controller::IRpcWrapperBase> rpcwrapper_Create(::vl::rpc_controller::RpcObjectReference ref, ::vl::rpc_controller::IRpcLifecycle* lc, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> ops);
		::vl::Ptr<::vl::glr::json::JsonNode> rpcjson_Serialize(const ::vl::reflection::description::Value& value);
		::vl::reflection::description::Value rpcjson_Deserialize(::vl::Ptr<::vl::glr::json::JsonNode> node);
		::vl::Ptr<::vl::rpc_controller::IRpcSerializer> rpcops_IRpcSerializer();
		::vl::Ptr<::vl::rpc_controller::IRpcObjectOps> rpcops_IRpcObjectOpsJson(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::Ptr<::vl::rpc_controller::IRpcObjectEventOps> rpcops_IRpcObjectEventOpsJson(::vl::rpc_controller::IRpcLifecycle* lc);
		::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> rpcops_IOps_CreateJson(::vl::rpc_controller::IRpcLifecycle* lc);

		static Rpc_PropDynamic& Instance();
	};

/***********************************************************************
Closures
***********************************************************************/

	struct __vwsnf1_Rpc_PropDynamic_rpclistener_RpcPropDynamic__IService_
	{
		::vl::rpc_controller::IRpcLifecycle* lc;
		::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> ops;
		::vl::rpc_controller::RpcObjectReference ref;

		__vwsnf1_Rpc_PropDynamic_rpclistener_RpcPropDynamic__IService_(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_ref);

		void operator()() const;
	};

	class __vwsnc1_Rpc_PropDynamic_serviceMain__RpcPropDynamic_IService : public ::vl::Object, public virtual ::RpcPropDynamic::IService
	{
	public:
		__vwsnc1_Rpc_PropDynamic_serviceMain__RpcPropDynamic_IService();

		::vl::WString _Value;
		::vl::WString GetValue() override;
		void SetValue(const ::vl::WString& value) override;
		void Signal() override;
	};

	class __vwsnc2_Rpc_PropDynamic_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectOps
	{
	public:
		__vwsnc2_Rpc_PropDynamic_rpcops_IRpcObjectOps__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::vint _slot = 0;
		::vl::Ptr<::vl::reflection::description::IValueDictionary> _byvalReturnValues;
		::vl::reflection::description::Value InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
		void EndInvokeMethod(::vl::vint slot) override;
		void ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold) override;
		void RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service) override;
	};

	class __vwsnc3_Rpc_PropDynamic_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectEventOps
	{
	public:
		__vwsnc3_Rpc_PropDynamic_rpcops_IRpcObjectEventOps__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::reflection::description::Value InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
	};

	class __vwsnc4_Rpc_PropDynamic_rpcops_IOps_Create__rpcops_IOps_Rpc_PropDynamic : public ::vl::Object, public virtual ::rpcops_IOps_Rpc_PropDynamic
	{
	public:
		__vwsnc4_Rpc_PropDynamic_rpcops_IOps_Create__rpcops_IOps_Rpc_PropDynamic(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::WString InvokeMethod_RpcPropDynamic__IService_GetValue(::vl::rpc_controller::RpcObjectReference ref) override;
		void InvokeMethod_RpcPropDynamic__IService_SetValue(::vl::rpc_controller::RpcObjectReference ref, const ::vl::WString& arg_value) override;
		void InvokeMethod_RpcPropDynamic__IService_Signal(::vl::rpc_controller::RpcObjectReference ref) override;
		void InvokeEvent_RpcPropDynamic__IService_ValueChanged(::vl::rpc_controller::RpcObjectReference ref) override;
	};

	class __vwsnc5_Rpc_PropDynamic_rpcwrapper_RpcPropDynamic__IService__RpcPropDynamic_IRpcWrapper_IService : public ::vl::Object, public virtual ::RpcPropDynamic::IRpcWrapper_IService
	{
	public:
		__vwsnc5_Rpc_PropDynamic_rpcwrapper_RpcPropDynamic__IService__RpcPropDynamic_IRpcWrapper_IService(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc, ::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> __vwsnctor_ops, ::vl::rpc_controller::RpcObjectReference __vwsnctor_proxyRef);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::rpc_controller::RpcObjectReference _ref;
		::vl::Ptr<::rpcops_IOps_Rpc_PropDynamic> _ops;
		void DisconnectFromLifecycle() override;
		~__vwsnc5_Rpc_PropDynamic_rpcwrapper_RpcPropDynamic__IService__RpcPropDynamic_IRpcWrapper_IService();
		::vl::WString GetValue() override;
		void SetValue(const ::vl::WString& value) override;
		void Signal() override;
	};

	class __vwsnc6_Rpc_PropDynamic_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcSerializer
	{
	public:
		__vwsnc6_Rpc_PropDynamic_rpcops_IRpcSerializer__vl_rpc_controller_IRpcSerializer();

		::vl::reflection::description::Value Serialize(const ::vl::reflection::description::Value& value) override;
		::vl::reflection::description::Value Deserialize(const ::vl::reflection::description::Value& value) override;
	};

	class __vwsnc7_Rpc_PropDynamic_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectOps
	{
	public:
		__vwsnc7_Rpc_PropDynamic_rpcops_IRpcObjectOpsJson__vl_rpc_controller_IRpcObjectOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::vint _slot = 0;
		::vl::Ptr<::vl::reflection::description::IValueDictionary> _byvalReturnValues;
		::vl::reflection::description::Value InvokeMethod(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint methodId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
		void EndInvokeMethod(::vl::vint slot) override;
		void ObjectHold(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint remoteClientId, bool hold) override;
		void RegisterService(::vl::vint typeId, ::vl::Ptr<::vl::reflection::IDescriptable> service) override;
	};

	class __vwsnc8_Rpc_PropDynamic_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps : public ::vl::Object, public virtual ::vl::rpc_controller::IRpcObjectEventOps
	{
	public:
		__vwsnc8_Rpc_PropDynamic_rpcops_IRpcObjectEventOpsJson__vl_rpc_controller_IRpcObjectEventOps(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::reflection::description::Value InvokeEvent(::vl::rpc_controller::RpcObjectReference ref, ::vl::vint eventId, ::vl::Ptr<::vl::reflection::description::IValueArray> arguments) override;
	};

	class __vwsnc9_Rpc_PropDynamic_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_PropDynamic : public ::vl::Object, public virtual ::rpcops_IOps_Rpc_PropDynamic
	{
	public:
		__vwsnc9_Rpc_PropDynamic_rpcops_IOps_CreateJson__rpcops_IOps_Rpc_PropDynamic(::vl::rpc_controller::IRpcLifecycle* __vwsnctor_lc);

		::vl::rpc_controller::IRpcLifecycle* _lc = nullptr;
		::vl::WString InvokeMethod_RpcPropDynamic__IService_GetValue(::vl::rpc_controller::RpcObjectReference ref) override;
		void InvokeMethod_RpcPropDynamic__IService_SetValue(::vl::rpc_controller::RpcObjectReference ref, const ::vl::WString& arg_value) override;
		void InvokeMethod_RpcPropDynamic__IService_Signal(::vl::rpc_controller::RpcObjectReference ref) override;
		void InvokeEvent_RpcPropDynamic__IService_ValueChanged(::vl::rpc_controller::RpcObjectReference ref) override;
	};
}

#if defined( _MSC_VER)
#pragma warning(pop)
#elif defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

#endif
