import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema32/Serialization_CollectionDict_Interface_InByval_OutByref";

export const json : (KnownTypeSchema | UnknownTypeSchema)[] = [
  {"$":"map","values":[[["Int32",1],{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2}],[["Int32",2],{"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2}],[["Int32",3],{"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2}]]},
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":-6},
  ["Int32",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  null,
  ["Int32",5],
  ["Int32",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  ["Int32",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int32",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int32",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":2},
  ["Int32",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  "A",
  "B",
  "C",
  "E",
  ["Int32",5],
  ["Int32",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  ["Int32",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int32",3],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int32",4],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":3,"typeId":2},
  "D",
  ["Int32",5],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2}
];
