import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema32/Serialization_Collection_Interface_InByval_OutByref";

export const json : (KnownTypeSchema | UnknownTypeSchema)[] = [
  {"$":"list","values":[{"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},{"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},{"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2}]},
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":-4},
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  ["Int32",4],
  ["Int32",5],
  ["Int32",0],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  ["Int32",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  ["Int32",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  ["Int32",3],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":2},
  ["Int32",4],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  "1",
  "2",
  "3",
  "5",
  {"$":"system::RpcObjectReference","clientId":1,"objectId":3,"typeId":-2},
  true,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":2},
  true,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":2},
  true,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":2},
  true,
  {"$":"system::RpcObjectReference","clientId":1,"objectId":4,"typeId":2},
  "4",
  true,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":2},
  false
];
