import type { KnownTypeSchema, UnknownTypeSchema } from "../DataSchema32/Serialization_PropDefaultInterfaceList";

export const json : (KnownTypeSchema | UnknownTypeSchema)[] = [
  {"$":"system::RpcObjectReference","clientId":1,"objectId":1,"typeId":-4},
  ["Int32",1],
  ["Int32",0],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":2,"typeId":5},
  {"$":"system::RpcObjectReference","clientId":1,"objectId":3,"typeId":-2},
  true,
  {"$":"system::RpcObjectReference","clientId":1,"objectId":4,"typeId":5},
  "A",
  false,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-4},
  ["Int32",3],
  ["Int32",0],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":1,"typeId":5},
  ["Int32",1],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":2,"typeId":5},
  ["Int32",2],
  {"$":"system::RpcObjectReference","clientId":2,"objectId":3,"typeId":5},
  null,
  ["Int32",1],
  ["Int32",0],
  {"$":"system::RpcObjectReference","clientId":1,"objectId":5,"typeId":5},
  {"$":"system::RpcObjectReference","clientId":1,"objectId":6,"typeId":-2},
  true,
  {"$":"system::RpcObjectReference","clientId":1,"objectId":7,"typeId":5},
  "A",
  false,
  null,
  null,
  {"$":"system::RpcObjectReference","clientId":2,"objectId":0,"typeId":-4}
];
